### ISSUE TITLE
[v2] Storage

### ISSUE THREAD

**Issue by elitan** [nhost/hasura-backend-plus#104]
```
PUT /storage/put (upload, create and overwrite) (check JWT token for access)
GET /storage/file/* (checks query token for access)
DELETE /storage/file/* (checks JWT token for access)
GET /fn/get-download-url/* (checks JWT token for access)
```

**Comment by pnfcre** [comment]
How about this?

```
POST /storage/upload (upload file)
GET /storage/:uuid/:filename?token=uuid (get raw file)
DELETE /storage/:uuid (delete file)
GET /storage/:uuid (get file object)
```

Where `GET /storage/:uuid` would return an object including file information (such as `created_at`, `uploaded_by`, etc) as well as `access_token` for downloading the image through `GET /storage/:uuid/:filename?token=uuid`?

😄

**Comment by elitan** [comment]
Hm, I don't think it's necessary to do the :uuid in the URL.

I would say:

```
POST /storage/upload (upload file), send JWT as header for verification
GET /storage/:file?token=uuid (get raw file)
GET /storage/:file (get metadata), send JWT as header for verification
DELETE /storage/:file (delete file), send JWT as header for verification
GET /storage/:file (get file object), send JWT as header for verification
```

since every instance of HBP will have its own domain name. I think that's enough for namespacing

**Comment by pnfcre** [comment]
Hmm, so people can't upload multiple files with the same filename? Or is `:file` referring to a UUID? Also there's a duplicate `GET /storage/:file` in that codeblock :sweat_smile:

**Comment by MarcelloTheArcane** [comment]
Does the [file upload documentation](https://nhost.github.io/hasura-backend-plus/api.html#upload-file) need updating? I'm getting 404 errors from the upload URL.

## Upload file
Upload, or overwrite, a file.

### Request
POST `/storage/o/<path-to-file>/`

### Response
```json
{
  "key": "<path-to-file>",
  "AcceptRanges": "bytes",
  "LastModified": "2020-01-01T01:02:03.000Z",
  "ContentLength": 12345,
  "ETag": "Etag",
  "ContentType": "<content-type>",
  "Metadata": {
    "token": "<auto-generated-access-token-uuid>"
  }
}
```

**Comment by elitan** [comment]
Do you get 404 but still that response? With `key`, `AcceptRanges` etc?

**Comment by MarcelloTheArcane** [comment]
No, I just get a plain 404, and the file isn't uploaded to the backend.

**Comment by elitan** [comment]
It should work.  :/

https://github.com/nhost/nhost-js-sdk/blob/master/src/Storage.ts#L19-L47

**Comment by MarcelloTheArcane** [comment]
```js
formData.append('file', file)
```

NOT

```js
formData.append(fileName, file)
```

😄
