### ISSUE TITLE
[v2] User db schema

### ISSUE THREAD

**Issue by elitan** [nhost/hasura-backend-plus#117]
# HBP user db

Here are some alternatives on how we should model our database schema related to users.

## Goal

In v2.0 authentication will cover the following login methods:

1. email/password
2. external OAuth providers (github, google, facebook)

## Why this issue?

Hasura Backend plus should aim to be both easy to get start with and easy to use, while at the same time be customizable to cover most use cases for different apps.

If we have a very oppinionated user schema strucuter, that would help developers get started quickly. But it might suffer apps in the long run due to lack of custom.

## Tables covered in this issue

- user-data (ex, `user_id`, `is_anonymous`)
- profile (ex, `organisation_id`, `name_of_turtle`)
- email/password (`email`, `password_hash`)
- user data for external providers (ex, `provider`, `display_name`, `email`).

These can be organized as:

- Authorization: user-data and profile
- Authentication: email/password and user data for external providers.

# Different approaches

### Schema

```sql
CREATE TABLE auth.user_accounts (
  id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  user_id uuid NOT NULL,
  email text UNIQUE,
  password text NOT NULL
);

CREATE TABLE auth.user_providers (
  id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  user_id uuid NOT NULL,
  auth_provider text NOT NULL,
  auth_provider_unique_id text NOT NULL
);

CREATE TABLE public.users (
  id uuid DEFAULT public.gen_random_uuid() NOT NULL PRIMARY KEY,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  display_name text NOT NULL,
  active boolean DEFAULT false NOT NULL,
  default_role text DEFAULT 'user'::text NOT NULL,
  avatar_url text,
  email text UNIQUE,
  secret_token uuid DEFAULT gen_random_uuid() NOT NULL UNIQUE,
  secret_token_expires_at timestamp with time zone DEFAULT now() NOT NULL,
  register_data jsonb,
  is_anonymous boolean DEFAULT false NOT NULL
);
```

### Thoughts

This allowed for a user to be able to login with either email/password or a single OAuth provider. The `users.display_name` was automatically populated with either the email (login email/pw) or the display name coming from the OAuth provider.

This made it easy for the front-end to request user data. All relevant data was in the `users` table such as `display_name`, `email`, `active`, `is_anonymous`, etc. You would also add custom fields (ex `team_id`) to the `users` table.

All in all, the mental model was easy. All important stuff related to frontend and Hasura permissions was in the `users` table. Also, when doing FK you would refer to the `users` table.

The downside was that `email` was present both in `user_accounts` and `users`. Not good.

### Schema

```sql
create table auth.user_accounts (
  id uuid default gen_random_uuid () not null primary key,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  user_id uuid not null,
  email text not null unique,
  password text not null
);

create table auth.user_providers (
  id uuid default gen_random_uuid () not null primary key,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  user_id uuid not null,
  auth_provider text not null,
  auth_provider_unique_id text not null
);

create table public.users (
  id uuid default public.gen_random_uuid () not null primary key,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  secret_token uuid default gen_random_uuid () not null unique,
  secret_token_expires_at timestamp with time zone default now() not null,
  active boolean default false not null,
  default_role text default 'user' ::text not null,
  is_anonymous boolean default false not null
  register_data jsonb,
  display_name text, -- used from user_providers (nullable)
  avatar_url text, -- used from user_providers (nullable)
  -- fill in your own custom user columns here
);
```

### Thoughts

Allow for email/password and multiple providers. It also makes the mental model easy because you know that the `users` table is where all important stuff goes. Permission variables for Hasura and Storage goes here, and all info of the users that you would want to show in the front-end.

### Schema

```sql

-- This table is technically not necessary
create table public.user_profiles (
  id uuid default gen_random_uuid () not null primary key,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  user_id uuid not null,
);

create table auth.user_providers (
  id uuid default gen_random_uuid () not null primary key,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  user_id uuid not null,
  auth_provider text not null,
  auth_provider_unique_id text not null,
  email text, -- info from provider
  display_name text, --info from provider
  avatar_url text -- info from provider
);

create table auth.user_accounts (
  id uuid default gen_random_uuid () not null primary key,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  user_id uuid not null,
  email text not null unique,
  password text not null
)

create table auth.users (
  id uuid default public.gen_random_uuid () not null primary key,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  active boolean default false not null,
  default_role text default 'user' ::text not null,
  register_data jsonb,
  is_anonymous boolean default false not null
  secret_token uuid default gen_random_uuid () not null unique,
  secret_token_expires_at timestamp with time zone default now() not null,
);
```

### Thoughts

Proper distinction between data based on what it's used for.

Authentication: `user_acconuts`, `user_providers` (login)
Authorization: `users` (Hasura and storage permissions)
Profile: `profile`

But:

How to get ex display_name and profile_url from the front-end (FE)?

Should we require FE to get it from a `auth_user_provider`? What about if a user first register using email/password? What would be the `display_name`?

I like this data model on a technical level, but not on a get started quick level.

# Schema naming

`public` is the schema where most app tables would go. It makes sense to place some tables that's not directly related to the app on another schema to make the Hasura console's tables view cleaner.

Two alternatives:

1. `auth`
2. `private`

### `auth`

All tables are related to auth. Also when writing queries/mutations one would prefix GraphQL with `auth_` which makes it clear what the mutation/query is about.

### `public`

It's the opposite to `public`, and `public` is the default schema for Hasura.

# None covered tables

Some tables are not being covered in this issuewon't be discussed in this issue. They are:

```sql
create table auth_providers (
  provider text not null primary key
);

create table refresh_tokens (
  refresh_token uuid not null primary key,
  created_at timestamp with time zone default now() not null,
  expires_at timestamp with time zone not null,
  user_id uuid not null
);

create table roles (
  role text not null primary key
);

create table public.user_roles (
  id uuid default gen_random_uuid () not null primary key,
  created_at timestamp with time zone default now() not null,
  user_id uuid not null,
  role text not null
);
```

**Comment by plmercereau** [comment]
I think I would go for option 3:
On one hand, the schema is quite complex indeed, but on the other hand the FE user would never have to tweak any of the tables in the `auth` schema, only the `public.profile` table. We would hide this complexity from them.

On options 1 and 2, the user will end up in wanting to modify the `users` table to add FKs, data columns, etc, and they would then need to keep track of what is required for HBP and auth, and what is custom. One mistake from them and HBP is down.

About the issue of getting the default `display_name` and `avatar_url` from possible multiple providers, I feel we would be forced to put some redundancy somehow. There are a few options:

1. forget about the users being able to have multiple auth providers, and put either a one-to-one between `user_providers` and `users`, or merge both tables. Not sure this is what we want

2. add `display_name` and `avatar_url` columns to the `users` table, and copy the information somehow from one of the auth providers. Not ideal

3. Reproduce what we did with roles and define a `default_provider_id` in the `user` table

Another point: If nobody plans to set multiple accounts per user, then the user <-> account relationship is one-to-one, and I wouldn't mind merging the tables into one.

**Comment by elitan** [comment]
On option 3: What would be the higher-order id (`user.id` or `profile.id`)? Let's say we create a new table `blog_posts` with 

```
id
title
body
user_id
```

Would `user_id` point to `auth.user.id` or `public.profile.id`? Since developers probably will interact mostly with the `profiles` table this might be a bit confusing.

Making the GraphQL query from profile to blog_posts, we would have to traverse through the users table.

--------

I completely agree about some columns are required for HBP to work. That they might get deleted is a valid concern.

**Comment by plmercereau** [comment]
Very good point... In my opinion developers should be able to delete the entire `auth` schema without any side effect on the `public` schema (other than setting the `public.profile.user_id` to null). I think they should use `public.profile.id`, but then, from their standpoint the name `profile` is indeed confusing.
I think it's rather a naming issue.

- If we merge `auth.accounts` and `auth.users` then the problem can be solved in using only two tables `auth.accounts` (instead of `auth.user_accounts` and `auth.users) and `public.users` (instead of `public.profiles`)

- if we don't (e.g. we want to have multiple accounts per user), we can either:
  - Use both `auth.users` and `public.users` in explaining the purpose of both table. Not ideal.
  - Keep `auth.users` and find another name for `auth.profiles`. Not ideal as developers will still want to use the name `user` in their mind
  - Change `public.profiles` to `public.user` and then find another name for `auth.users`. But which one?

**Comment by pnfcre** [comment]
I have no strong opinion on this, but I agree with your discussion so far. I'm convinced that `auth` is a better choice for naming the schema.

**Comment by elitan** [comment]
@plmercereau Good points! I like this discussion.

What about the following:

```sql
-- No one should need to add/remove/edit any column
create table auth.accounts (
  id uuid default public.gen_random_uuid () not null primary key,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  user_id uuid not null,
  active boolean default false not null,
  email citext unique, -- could be null if account only uses a provider
  password_hash text, -- coult be null if account only uses a provider
  default_role text default 'user' ::text not null,
  is_anonymous boolean default false not null
  custom_register_data jsonb,
  otp_secret text,
  mfa_enabled boolean default false not null
  ticket uuid default public.gen_random_uuid () not null,
  ticket_expires_at timestamp with time zone default now() not null,
);

-- No one should need to add/remove/edit any column
create table auth.user_providers (
  id uuid default public.gen_random_uuid () not null primary key,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  account_id uuid not null,
  auth_provider text not null,
  auth_provider_unique_id text not null
);

-- EDIT ALL THE FIELDS
create table public.users (
  id uuid default public.gen_random_uuid () not null primary key,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  display_name text, -- example column, might be part of the init boilerplate
  avatar_url text -- example column, might be default but deletable.
  -- more app specific user columns.
  -- ex company_id uuid.
  -- HBP would take custom permissions from here
);
```

HBP would take custom permission variables from the last `public.users` table.

The other three tables should never be touched.

This is easy to reason about. Developers would only need to worry about `public.users`.

**Comment by elitan** [comment]
Here is a complete proposal:

```sql
create extension if not exists pgcrypto;
create extension if not exists citext;
create schema auth;

create function set_current_timestamp_updated_at ()
  returns trigger
  language plpgsql
  as $$
declare
  _new record;
begin
  _new := new;
  _new. "updated_at" = now();
  return _new;
end;
$$;

-- EDIT ALL THE FIELDS
create table public.users (
  id uuid default public.gen_random_uuid () not null primary key,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  display_name text, -- example column, might be part of the init boilerplate
  avatar_url text -- example column, might be default but deletable.
);


create table auth.providers (
  provider text not null primary key
);

create table auth.roles (
  role text not null primary key
);

-- No one should need to add/remove/edit any column
create table auth.accounts (
  id uuid default public.gen_random_uuid () not null primary key,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  user_id uuid not null references public.users (id) on delete cascade on update cascade,
  active boolean default false not null,
  email citext unique CONSTRAINT proper_email CHECK (email ~* '^[A-Za-z0-9._%-]+@[A-Za-z0-9.-]+[.][A-Za-z]+$'),
  password_hash text, -- coult be null if account only uses a provider
  default_role text default 'user' ::text not null references auth.roles (role) on delete restrict on update cascade,
  is_anonymous boolean default false not null,
  custom_register_data jsonb,
  otp_secret text,
  mfa_enabled boolean default false not null,
  ticket uuid default public.gen_random_uuid () not null,
  ticket_expires_at timestamp with time zone default now() not null
);

create table auth.refresh_tokens (
  refresh_token uuid not null primary key,
  created_at timestamp with time zone default now() not null,
  expires_at timestamp with time zone not null,
  account_id uuid not null references auth.accounts (id) on delete cascade on update cascade
);

create table auth.account_roles (
  id uuid default gen_random_uuid () not null primary key,
  created_at timestamp with time zone default now() not null,
  account_id uuid not null references auth.accounts (id) on delete cascade on update cascade,
  role text not null references auth.roles (role) on delete restrict on update cascade,
  constraint user_roles_account_id_role_key unique (account_id, role)
);

-- No one should need to add/remove/edit any column
create table auth.account_providers (
  id uuid default public.gen_random_uuid () not null primary key,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  account_id uuid not null references auth.accounts (id) on delete cascade on update cascade,
  auth_provider text not null references auth.providers (provider) on delete restrict on update restrict,
  auth_provider_unique_id text not null,
  constraint account_providers_auth_provider_auth_provider_unique_id_key unique (auth_provider, auth_provider_unique_id),
  constraint account_providers_account_id_auth_provider_key unique (account_id, auth_provider)
);

create trigger set_public_users_updated_at
  before update on public.users
  for each row
  execute procedure set_current_timestamp_updated_at ();

create trigger set_auth_accounts_updated_at
  before update on auth.accounts
  for each row
  execute procedure set_current_timestamp_updated_at ();

create trigger set_auth_account_providers_updated_at
  before update on auth.account_providers
  for each row
  execute procedure set_current_timestamp_updated_at ();

INSERT INTO auth.roles (ROLE)
  values ('user');

insert into auth.roles (role)
  values ('anonymous');

insert into auth.providers (provider)
  values ('github'), ('facebook'), ('twitter'), ('google');

```

**Comment by plmercereau** [comment]
I think the remaining issue is to move the one-to-one foreign key in the `users` table instead of the `accounts` table, then we're good

**Comment by elitan** [comment]
> I think the remaining issue is to move the one-to-one foreign key in the `users` table instead of the `accounts` table, then we're good

Remind me again, why do we want this? What's the benefit?

My intuition is to have `users` as the parent table. That's probably the table that most users will interact with. The most common case, I think, would be when developers manually delete a entry in the `users` table, and that deletion should cascade through the system. Which it does now with the current FK schema setup.

**Comment by plmercereau** [comment]
I tried the change yesterday night, and I now agree with you - it is
already the way it should be.
Maybe change the Hasura relationship so one user has one account? What's
the case of an user having multiple accounts?

**Comment by plmercereau** [comment]
I tried the change yesterday night, and I now agree with you - it is already the way it should be.

Maybe change the Hasura relationship so one user has one account? What's the case of an user having multiple accounts?

**Comment by elitan** [comment]
Got it.

Agreed, a user should only be having one account.

I guess we can sett a `UNIQUE` constraint on `accounts.user_id` to solve it.

**Comment by plmercereau** [comment]
Yes, and change the Hasura array relationship to an object relationship, from `accounts` to `account`

**Comment by elitan** [comment]
Yes I'm on it!

**Comment by plmercereau** [comment]
Last point:
Should the `/auth/account/delete` endpoint delete both user and account, or only the account?

In keeping the user we can keep all the data the developper would have designed in the public schema, but then the dev will need to make a decision on what to do when it happens, e.g. soft-delete, setting personal information to null, deleting the record in the users table...

**Comment by elitan** [comment]
Let's continue the discussion about delete here: https://github.com/nhost/hasura-backend-plus/issues/153
