### ISSUE TITLE
[v2] OK with keeping TS in production?

### ISSUE THREAD

**Issue by plmercereau** [nhost/hasura-backend-plus#130]
V2 is written in TypeScript. A common practice in TS is to run the code in developpement with `ts-node`, and then to compilte the TS code into javascript with `tsc`, so node is invoked in production. However some started to use `ts-node` in production, as the performance loss between `ts-node` and `node` is negligible. I think this is also the general trend as even `deno` will run TS natively.

On the other hand, if we want to make a clear discinction between TS in dev and JS in prod, we have to keep the separation between `dependencies` and `devDependencies` in the `package.json`file.

The building of the Docker file would also become complicated, as we would need to create a multi-staged, first to get all the TS packages and to transpile, second to copy the generated `dist` files into the production stage.

I see also a main caveats: if production is on node, the developper won't be able to define custom TS code such as storages rules - but it's a more complex issue, I'll come to that on a separate issue.

If you are fine with the statu quo (everything in TS), then please close the issue. This is I think the simplest solution. Otherwise let's talk.

**Comment by elitan** [comment]
I'm fine with `ts-node`. Sounds simple.
