### ISSUE TITLE
[next] custom validation of custom fields

### ISSUE THREAD

**Issue by plmercereau** [nhost/hasura-backend-plus#142]
Currently the `USER_FIELDS` environment variable allows to send custom user data upon registration, and to add `x-<field-name>` key-values to the Hasura JWT claims.
`USER_FIELDS` is a list of comma separated values that represents columns that should exist in the `public.users` table.

However we may want to add some custom validation on those fields at registration time too. For instance, some custom fields should be strings, while other should be numbers, and some are required, other are optional.

A single environment variable may not be enough. We could either let the developper define series of environment variables, or create a `customFields.js` file in the custom directory, that would define a Joi validation schema. Or another system...

I don't think this is something that must be in the initial v2 release, but something we could discuss at a later stage.

**Comment by elitan** [comment]
These validations can be added at postgres levels using checks.

https://hasura.io/docs/latest/graphql/core/databases/postgres/schema/data-validations.html#using-postgres-check-constraints
