### ISSUE TITLE
[v2] don't create endpoints when not used

### ISSUE THREAD

**Issue by plmercereau** [nhost/hasura-backend-plus#152]
For instance, no need to mount unused express middlewares such as
- `auth/account/activate` when auto-activation on registration is on
- `/auth/jwks` when not using an RSA algorithm
- GitHub oauth when not configured
- `/storage` when not used

... and so on

**Comment by elitan** [comment]
Agreed.

How do we do this nicely? 

Do we do it in the `index.ts` files? Ex here:

```
import { Router } from 'express'

import deleteAccount from './delete'
import activateAccount from './activate'

export default Router()
.get('/activate', activateAccount)
.post('/delete', deleteAccount)
```

Or in each function handling the request. Ex here:

```
[...]
async function activateUser({ query }: Request, res: Response): Promise<unknown> {

// check here

[...]
```

**Comment by plmercereau** [comment]
We should do it in the `index` files, or at least in the file defining the routes, and not in each handler, as the handler would be mounted in express already.
The idea is to avoid mounting handlers so the deactivated routes will not even exist
