### ISSUE TITLE
[next] Ability for the user to unsubscribre / delete their user/account

### ISSUE THREAD

**Issue by plmercereau** [nhost/hasura-backend-plus#153]
This env var would deactivate the `/auth/account/delete` endpoint.

Tentative name: `ALLOW_UNSUBSCRIBE` with defaults to true

**Comment by elitan** [comment]
Yes, but I am not sure if `UNSUBSCRIBE` is good.

How about `ALLOW_USER_SELF_DELETE`.

Also, I would default this to `false` for devs to properly implement user deletions and avoid unexpected effects of users suddenly self-deleting them selfs.

**Comment by plmercereau** [comment]
I don't know, it would depend on the main common practice. I feel most of the applications allow unsubscription, which is mandatory in terms of data privacy and rights.

`ALLOW_USER_SELF_DELETE` is probably misleading as the user is not deleted so far, only the account

**Comment by plmercereau** [comment]
in general terms, env vars describing actions don't need to include `USER` as all the HBP actions are performed by the users

**Comment by elitan** [comment]
Ah, so you only want to delete the `auth.accounts` data and not the `public.users` data.

That sounds like trouble to maintain.

How about we just skip the whole `/account/delete` for now until we get feedback from devs using HBP?

**Comment by plmercereau** [comment]
sure, let's remove the endpoint, keep this issue open and wait for feedback.
The action is somehow easy to perform without HBP with a `delete` mutation.

Side note: JWT invalidation could be a concern to keep in mind though, but I still haven't found time to understand the refresh mechanism, that may solve the problem

**Comment by plmercereau** [comment]
What we can also do is to define a `DELETE_ACCOUNT_ONLY` env var, defaulted to false:

- when true, delete the `public.users` record - it will then cascade delete the `auth.account` record
- when false, delete the `auth.accounts` record - the `public.users` is kept

**Comment by elitan** [comment]
Yea that would work.

**Comment by hawkeye64** [comment]
I suggest adding a `deleted_at` (timestamp with timezone) column. If not null, then user is active. Otherwise treat as deleted so other relationships don't get messed with.

**Comment by RubenVanEldik** [comment]
Deleting an account is quite a permanent action, it some scenario's it might be preferable to ask the user for their password as well. This way the probability of an accidental or malicious account deletion are reduced.

This could be done by adding another environment variable (e.g. `ALLOW_USER_SELF_DELETE_PASSWORD`) or a `password` option besides `true` and `false` for `ALLOW_USER_SELF_DELETE`.

I would love to hear what others think about this!

**Comment by elitan** [comment]
I like both of the last two ideas.

For the password to delete I think we should even default to that one now.

**Comment by RubenVanEldik** [comment]
Yeah, @hawkeye64's idea is great!

I was thinking today about implementing the delete functionality, and doing a hard delete of all user data is often not the best solution. Using a Postgres trigger (based on a `deleted_at` column) to remove all PIA when an account is deleted is probably the easiest way to do this for most applications.

**Comment by RubenVanEldik** [comment]
@elitan, do you think this could be added to HBP2 or is this something for a future HBP3?

Because the password requirement as default would make this a breaking change, if the password requirement was opt-in this feature could be a minor upgrade for HBP2.

**Comment by RubenVanEldik** [comment]
Btw, I would love to help out with HBP, but I don't have any experience with Typescript. To get started I would love to help with improving the documentation. Are there any sections of the documentation that are currently high on your priority list and that I could take over?

**Comment by elitan** [comment]
> I suggest adding a `deleted_at` (timestamp with timezone) column. If not null, then user is active. Otherwise treat as deleted so other relationships don't get messed with.

I think we're going to change to this behavior in the next major release (v3).

**Comment by elitan** [comment]
We’ve decided to only fix bugs and refactors on Hasura Backend Plus from now on because we’re working on a new auth + storage service for Hasura. Currently, these new repositories are private but will be open-sourced soon. 

We’ll have your issue in mind when developing the new services. So thanks for filing this issue

 This means I’ll close this issue for now.
