### ISSUE TITLE
[next] Allow manual validation of new registrations

### ISSUE THREAD

**Issue by plmercereau** [nhost/hasura-backend-plus#158]
In some cases, the developper may want to manually validate new registrations.

We could either add an optional additional step before allowing any type of login (standard, totp, oauth...) that would check a boolean value in the accounts table, or to implement some kind of an invitation feature where only invited people can start the registration process.

This is at the idea phase, so any comment or suggestion is welcome!

**Comment by elitan** [comment]
Isn't the `account.active` enough for developers who manually want to validate new users?

For invitation: Yes, that's interesting. We could let invitations act just like registration. 

1. Someone invites [user-email]. 
2. HBP creates the user/account but flags it as `invite=pending` or similar.
3. HBP sends an email to [user-email].
4. InvUser clicks on a link in the email.
5. InvUser opens up an HBP hosted form.
6. InvUser sets a password and clicks "register"
7.  InvUser is now registered and activated with email/password.

**Comment by plmercereau** [comment]
`account.active` is not enough as:
- disable auto activation currently means we want to verify the email -> any user can still activate with a valid email adress
- oauth activates anything

Good start for considering invitations!!!

**Comment by elitan** [comment]
> disable auto activation currently means we want to verify the email -> any user can still activate with a valid email adress

That's fine. If you don't want users to be able to register you should instead disable the `/auth/register` endpoint for public use, and only allow to use the `/auth/register` andpoint using the `admin-secret`. (https://github.com/nhost/hasura-backend-plus/pull/276)

> oauth activates anything

I think that's fine too. What we could do is to set a `ALLOWED_EMAIL_DOMAINS` env var to only allow users from specific domain(s) (ex: `tesla.com`) to login and use the service.

**Comment by elitan** [comment]
> In some cases, the developer may want to manually validate new registrations.

I've not come across this use case from any user yet. Happy to reopen once we have a real-life use case.
