### ISSUE TITLE
Upgrade joi package to @hapi/joi

### ISSUE THREAD

**Issue by donnerc** [nhost/hasura-backend-plus#161]
According to https://www.npmjs.com/package/joi, the `joi` package is deprecated and should be replaced by `@hapi/joi` for security reasons.

**Comment by elitan** [comment]
This will be fixed in v2 (https://github.com/nhost/hasura-backend-plus/blob/v2/package.json#L26)

You can view v2 here: https://github.com/nhost/hasura-backend-plus/tree/v2
