### ISSUE TITLE
[next] reflect Hasura JWT options in HBP

### ISSUE THREAD

**Issue by plmercereau** [nhost/hasura-backend-plus#163]
See Hasura's [documentation](https://hasura.io/docs/1.0/graphql/manual/auth/authentication/jwt.html), in particular:
- [`claims_namespace`](https://hasura.io/docs/1.0/graphql/manual/auth/authentication/jwt.html#claims-namespace)
- [`claims_namespace_path`](https://hasura.io/docs/1.0/graphql/manual/auth/authentication/jwt.html#claims-namespace-path)
- [`claims_format`](https://hasura.io/docs/1.0/graphql/manual/auth/authentication/jwt.html#claims-format)
- [`audience`](https://hasura.io/docs/1.0/graphql/manual/auth/authentication/jwt.html#audience)
- [`issuer`](https://hasura.io/docs/1.0/graphql/manual/auth/authentication/jwt.html#issuer)

**Comment by mirzap** [comment]
Also, I would suggest to implement all available JWT sign options. I have slightly modified HBP to include them, since I need `audience` and `issuer`. Check this interface for example:
https://github.com/panva/jose/blob/master/types/index.d.ts#L442

But still thinking how to implement jwt claim namespaces.

**Comment by plmercereau** [comment]
Good idea! I'll look into that. I'm not sure we would set all available sign options at once, but we could definitely start with `audience` and `issuer` as they also configurable in Hasura.

**Comment by elitan** [comment]
Why do we need this?

What's the use case?

**Comment by elitan** [comment]
Closing for now. Happy to re-open if a specific problem regarding this comes up.
