### ISSUE TITLE
Custom JWT claim namespace

### ISSUE THREAD

**Issue by mirzap** [nhost/hasura-backend-plus#172]
Is it possible to have custom JWT claim namespace? Since it's configurable in [Hasura](https://hasura.io/docs/1.0/graphql/manual/auth/authentication/jwt.html#claims-namespace) it would be nice to support that too in v2. 

Maybe introducing a new env variable, eg. `JWT_CLAIM_NAMESPACE` with a default value in config set to `https://hasura.io/jwt/claims`

https://github.com/nhost/hasura-backend-plus/blob/f63e963f2a742a60443008290b911b5cb1bd0dbf/src/shared/helpers.ts#L47

**Comment by plmercereau** [comment]
Hi @mirzap,
Yes, we are already considering it, see #163.
Hopefully we'll make some time to set this up soon.
Thanks for your suggestion
