### ISSUE TITLE
Easiest way to send emails?

### ISSUE THREAD

**Issue by KJDEV-PL** [nhost/hasura-backend-plus#174]
Hello.
What's the easiest and free way to send activation and password reset emails?
I am a hobby flutter programmer and I need a functional backend.
Regards.

**Comment by plmercereau** [comment]
Hello @KJDEV-PL, 

We are working on tackling this recurrent challenge in the version 2 of Hasura-Backend-Plus. Hopefully we will release it soon. In the meantime, you can have a look at the [v2 branch](https://github.com/nhost/hasura-backend-plus/tree/v2).

We already coded this feature, that will be optional and deactivated by default.

The developper would need to configure an SMTP server through environment variables. It comes with [basic email templates](https://github.com/nhost/hasura-backend-plus/tree/v2/custom/emails) that would be customisable in mounting them to a docker volume.

I think the workflow is what you're looking for:
1. account registration
2. create an unactivated account
3. send an activation email with an activation link (time-bound ticket)
4. activation through an http GET with email+ticket
5. redirection to a custom url

Best

**Comment by KJDEV-PL** [comment]
Hello @plmercereau.

Very interesting.
Yes, that's what I'm looking for.
Is there any approximate date of the first official v2 release?

**Comment by plmercereau** [comment]
I don't know, we basically have to improve tests and documentation, no deadline is fixed yet but I would say in a couple of weeks, hopefully less, a bit more if we encounter some bumps on the road

**Comment by hawkeye64** [comment]
There are a couple of workflows here. Email via SMTP is one, but using a service is another.

I have modified my config.js for the following:
```
// EMAIL
exports.EMAIL_API_KEY = process.env.EMAIL_API_KEY ? process.env.EMAIL_API_KEY : ''
exports.EMAIL_SEND_FROM_NAME = process.env.EMAIL_API_KEY ? process.env.EMAIL_SEND_FROM_NAME : ''
exports.EMAIL_SEND_FROM_EMAIL = process.env.EMAIL_SEND_FROM_EMAIL ? process.env.EMAIL_SEND_FROM_NAME : ''
exports.EMAIL_REGISTRATION_TEMPLATE_ID = process.env.EMAIL_API_KEY ? process.env.EMAIL_REGISTRATION_TEMPLATE_ID : 1
```
Using [SendInBlue](https://www.sendinblue.com/) email service

Also, instead of using name to login, I have change my workflow to use email.

Created an `emailer.js`:

```js
const SibApiV3Sdk = require('sib-api-v3-sdk')

const {
  EMAIL_API_KEY,
  EMAIL_SEND_FROM_EMAIL,
  EMAIL_SEND_FROM_NAME,
  EMAIL_REGISTRATION_TEMPLATE_ID
} = require('../config')

const EMAIL_TYPE = {
  TRANSACTIONAL: 0
}

class MwqEmailer {
  /**
   * Email client might support multiple API's, i.e Transactional, Campaigns etc.
   * @param type
   * @returns {MwqEmailer}
   */
  init (type) {
    const client = SibApiV3Sdk.ApiClient.instance
    const apiKey = client.authentications['api-key']
    // console.log('API KEY: ', EMAIL_API_KEY);
    apiKey.apiKey = EMAIL_API_KEY

    switch (type) {
      default:
        this.api = new SibApiV3Sdk.SMTPApi()
        break
    }
    return this
  }

  sendTransactionalEmail (toEmail, toName, templateId, params) {
    const smtpEmailProps = {
      sender: {
        name: EMAIL_SEND_FROM_NAME,
        email: EMAIL_SEND_FROM_EMAIL
      },
      to: [{
        name: toName,
        email: toEmail
      }],
      templateId,
      params
    }

    return new Promise((resolve, reject) => {
      this.api.sendTransacEmail(smtpEmailProps).then(function (data) {
        resolve(data)
      }, function (error) {
        console.error(error.response.res.text)
        reject(error.response.res.text)
      })
    })
  }

  sendRegistrationEmail (toEmail, toName, token) {
    return this.sendTransactionalEmail(toEmail, toName, EMAIL_REGISTRATION_TEMPLATE_ID, {
      TOKEN: token
    })
  }
}

exports.EMAIL_TYPE = EMAIL_TYPE
exports.emailer = new MwqEmailer()
```
then it's used in `local.js`:

```js
const {
  emailer,
  EMAIL_TYPE
} = require('../email/emailer')
// ...
```

after creating the user account:

```js
  try {
    await graphql_client.request(mutation, {
      user: {
// ...
  } catch (e) {
    console.error(e)
    return next(Boom.badImplementation('Unable to create user.'))
  }

  try {
    const res = await emailer.init(EMAIL_TYPE.TRANSACTIONAL).sendRegistrationEmail(email, username, emailValidationToken)
    console.log(res)
  } catch (e) {
    console.log(e)
    return next(Boom.badImplementation('Unable to send validation email.'))
  }

  res.send('OK')
```
The SendInBlue account has been set up to call the `activate-account` end-point with the `emailValidationToken`

**Comment by plmercereau** [comment]
Every http API is different from one email service to another, but most use SMTP, including SendInBlue.
I would rather use smtp when possible, and when no smtp is available, then we could consider coding custom [nodemailer transports] (https://nodemailer.com/plugins/create/#transports).
