### ISSUE TITLE
Social authentication improvement suggestion

### ISSUE THREAD

**Issue by mirzap** [nhost/hasura-backend-plus#194]
Hello,

First of all I want to say thank you for this great package. Also, I really like HBPs social authentication feature. That's why I have improvement suggestion. I would suggest extracting this feature into separate package, as well as independent packages for each driver.

Advantages:
- easier to contribute with a new social "driver" addon for HBP
- less unnecessary dependencies. most users will use 1 or 2 authentication methods, but they are required to download bunch of packages they don't use

Disadvantages:
- since v2 is still in development, I don't see any issues here. It would be better to do this before official release.

**Comment by elitan** [comment]
Thanks for the encouraging words!

On v2 it's pretty easy to add new drivers (providers). Ex look at this PR adding Facebook as a new provider:
https://github.com/nhost/hasura-backend-plus/pull/191/files

I agree with your point about unnecessary dependencies, but I think it's neglectable and will just add complexity for users and maintainers of HBP for no other benefit than saving a few kB.
