### ISSUE TITLE
workflow for anonymous user

### ISSUE THREAD

**Issue by hawkeye64** [nhost/hasura-backend-plus#196]
Any chance updating the docs for the anonymous user login workflow? This is a new concept for me and I think it's something I want, but just don't understand the work flow.
If you explain here, I can update the docs (if I get it).
Thanks.

**Comment by elitan** [comment]
We are mimicking Firebase's anonymous users. More info here:
https://firebase.google.com/docs/auth/web/anonymous-auth

It would be awesome if you would want to contribute with docs. Just note that we are working in the `v2` branch right now. https://github.com/nhost/hasura-backend-plus/tree/v2

Hmm, now when I think about it I don't think we yet have implemented anonymous users in v2.

**Comment by elitan** [comment]
Yea, so we have not yet implemented anonymous users in v2. However, we got the `is_anonymous` column for `auth.accounts` so it's prepared for.

If you want to contribute here is some inspiration: 
https://github.com/nhost/hasura-backend-plus/blob/master/src/auth/local.js#L288-L384

**Comment by hawkeye64** [comment]
@elitan Thanks for the link. It looks good. I am not familiar with Firebase, but it's a good start.
