### ISSUE TITLE
[next] Allow for storing refresh tokens client side

### ISSUE THREAD

**Issue by elitan** [nhost/hasura-backend-plus#197]
Right now in v2 we are storing refresh tokens as HttpOnly cookie.

The problem is that we are unable to reliably logout users that are offline with this approach. Since we can not send a `/logout` request and clear the refresh token cookie when we are offline.

The only option, as I see it, for **reliably** logout users that are offline is to store the refresh token client side, and remove it once the user logs out.

**Comment by weyert** [comment]
Reliably logout would always problematic while the user is using the application offline?  Locally storing the token seems to conflict with using a HttpOnly cookie?

**Comment by elitan** [comment]
It would either be storing the refresh token locally, or save the refresh token as a HttpOnly cookie.

**Comment by elitan** [comment]
This is implemented.
