### ISSUE TITLE
[next] validate and transform S3 objects

### ISSUE THREAD

**Issue by plmercereau** [nhost/hasura-backend-plus#213]
Extend storage rules for instance to:
- allow only a specific type of files, e.g. images
- limit size
- transform the object e.g. resize an image

**Comment by elitan** [comment]
**allow only a specific type of files, e.g. images**
We can do this with rules. Either `file.endsWith('.png')` or `resource.ContentType === 'image/png'`. This could also be handled client side with `<input type="file" name="myImage" accept="image/*" />`

**limit size**
`resource.ContentLength < 100000` and/or client side check

**transform the object e.g. resize an image**
This, I think, should not be handled through HBP. We should assume that files can be uploaded to S3 outside of HBP. Just like Hasura assumes, and manages, data inserts outside their GraphQL API. We should instead use webhooks + cloud functions.

**Comment by plmercereau** [comment]
Your two first points are perfect examples for the documentation!
Client checks are out of score and are alone insecure.
I'll dig further into details about your third point

**Comment by elitan** [comment]
I'll close this one in favour of https://github.com/nhost/hasura-backend-plus/issues/347

**Comment by plmercereau** [comment]
Size or file type filtering won't be solved by webhooks I think

**Comment by elitan** [comment]
Maybe I was too quick but isn't the file type filtering working right now?
