### ISSUE TITLE
[next] event trigger scheduler

### ISSUE THREAD

**Issue by plmercereau** [nhost/hasura-backend-plus#214]
It's supposed to be in the Hasura roadmap, but if not planned in the close future, it could be part of HBP

**Comment by elitan** [comment]
I don't think we should include a scheduler in HBP since I think HBP should be able to run with "Google Scale" using Google Cloud Run. And since Google Cloud Run scale down to zero it does not make sense to include a cron scheduler in HBP.

**Comment by plmercereau** [comment]
Good point - that is likely to apply for a scheduler in Hasura 😆 
The logical alternative that I see to run a scheduler while running HBP on GC run is GC schedule, probably very effective but not an open-source panacea

**Comment by elitan** [comment]
I can see that it makes more sense to not run Hasura using ex Google Cloud Run and scale down to zero because of ex web socket subscriptions. So it make more sense to place a scheduler on a platform that is "always online" and does not scale down to zero like an API.

**Comment by elitan** [comment]
Yes, Hasura seem to implement the scheduler in their v1.3
https://github.com/hasura/graphql-engine/milestone/27
