### ISSUE TITLE
[next] wait a few seconds to delete (or set expires_at) used refresh tokens

### ISSUE THREAD

**Issue by elitan** [nhost/hasura-backend-plus#220]
If I refresh the front end super fast I can send two request to HBP with the same refresh token. I think what happens is that I send a request, the server remove the cookie and then, because I spam refresh, the request get canceled. So i don't get the new refresh token.

Next request, I am logged out :/

**Comment by aaronhayes** [comment]
I seem to see a similar issue. Does the same problem occur with multiple tabs?

**Comment by elitan** [comment]
It should not be related to multiple tabs since the cookie for the backend is shared across tabs. 

It's more an issue of a race condition. 

- Req #1 with token #1 `/token/refresh` is being sent.
- Req #1 hits the backend server, deletes the current refresh token (token #1) and is starting to sending back the new refresh token (token #2).
- Browser cancles Req #1.
- Req #2 with token #1 `/token/refresh` is being sent. Notice that we still use token #1 since we cancled Req #1.
- Req #2 hits the backend server, token #1 has already been deleted so the backend rejects the request with 404.
- User gets logged out.

**Comment by elitan** [comment]
Will be solved in client libraries: https://github.com/nhost/nhost-js-sdk/issues/65
