### ISSUE TITLE
[v2] Use 3rd party cookies or not?

### ISSUE THREAD

**Issue by elitan** [nhost/hasura-backend-plus#228]
Hasura Backend Plus (HBP) version 2 currently saves the `refresh_token` as a httpOnly cookie. This effectively makes the `refresh_token` cookie a third party cookie since HBP might not always run under the same domain as your frontend. HBP might, for example, be running on https://backend-example.nhost.app and your frontend will be running at [https://lunarspace.se](https://www.lunarspace.se/).

This causes problem, since more and more browsers block 3rd party cookies due to privacy concerns and aggressive ad tracking with 3rd party cookies. Brave, [Firefox](https://blog.mozilla.org/blog/2019/09/03/todays-firefox-blocks-third-party-tracking-cookies-and-cryptomining-by-default/) and [Safari](https://www.theverge.com/2020/3/24/21192830/apple-safari-intelligent-tracking-privacy-full-third-party-cookie-blocking) block 3rd party cookies.

Even [Chrome will block 3rd party cookies eventually](https://blog.chromium.org/2020/01/building-more-private-web-path-towards.html).

This leaves us with two options:

## Option 1 - Skip cookies

Instead of using cookies refresh tokens will be saved client side in ex localStorage. This is how Hasura Backend Plus version 1 works.

Pros:
- Works when backend and frontend is on different domains.
- Simple to get started.
- Less configuration.

Cons:
- We need to rely more on the client side libs to save the refresh tokens.
- We need to trix a bit when redirecting users (since we need to attach the refresh token in the redirect)
- Loose some flexibility with the storage

## Option 2 - Keep cookies

We could keep the current set up with cookies but leave it to the developers, the users of HBP, to always make sure that HBP and their frontend runs under the same domain. If you have HBP on `backend.example.com` and your frontend on `example.com` the current strategy works. However, as soon as you run your frontend on any other domain than `example.com`, ex preview environment on Netlify/Vercel or localhost, the cookie from `backend.example.com` will be classed as a 3rd party cookie and might very well be blocked.

Pros:

- More storage flexibility
- Simple to manage refresh tokens

Cons:
- Harder to get started
- More configuration

-----

### Storage flexibility

With cookies, we can rely on cookies on `<img />` tags etc for there to be a cookie that we can evaluate and resolve permissions around. This makes for a bit more flexibility.
 
If we don't use cookies, we would instead issue an access token attached to each file. You will only be able to get the access token if you have read/get permission. But, once you have the access token and the file, you can send that to anyone (without read/get permission) and they will be able to get the file. This is how Google Firebase handles their storage system. The access token is a non-guessable token, and if you get it, you are trusted by the system to share it.

You can, as admin, at any time revoke an access token and generate a new one.

------

I would love to get your thoughts on this, we build HBP for you!

What do you think?

**Comment by defrex** [comment]
IMO, the best bet is to run HBP and the client on the same domain. That likely means adding custom domain support to nhost.io (if it's not there already).

Something to keep in mind is SSR scenarios. It's often necessary to make authenticated API requests from a node.js backend, in addition to a frontend client. HTTP-only cookies on a wildcard subdomain is a good solution here. They work well for the client and can be read and repeated in the SSR context to perform authenticated requests there.

In order to get SSR working in HBP v1 I had to store the tokens in an HTTP cookie, which meant a re-implementation.

**Comment by elitan** [comment]
I think we'll use cookies.

For [Nhost](https://nhost.io), we already have the ability for custom domain names for HBP, it's just not in the UI, but will be added!
