### ISSUE TITLE
Send email confirmation again

### ISSUE THREAD

**Issue by KJDEV-PL** [nhost/hasura-backend-plus#237]
Hello it is me again :)

I think it would be useful to add in `/auth/activate` options to generate a new ticket when the old one expires and send a confirmation message again, or to automatically delete an unconfirmed account and give the opportunity to create a new one.

Example: Registers in the application, but I can't log in to the email inbox right now. Once the ticket's validity has expired, you cannot activate your account, you cannot log in to your account, or you cannot create a new account at this email address.

Greetings.

**Comment by elitan** [comment]
Right, make sense!

Maybe we should set a much longer expiration on the ticket on registration. Like 14 days or so?

**Comment by plmercereau** [comment]
Yes, the easiest way to fix this would be to allow the user to register again, e.g. in `register.ts` to adapt the lines
```js
if (account) {
    throw Boom.badRequest('Account already exists.')
  }
````
to something like `if (account?.active) ... -> badrequest`, and to handle an update of the 'pending' unactivated account if `active` is false.

**Comment by elitan** [comment]
What about requesting a new password, and setting the new password will also activate the account?

**Comment by elitan** [comment]
1. Send out activation email (again) if account exist but is not activated.
2. Resetting password on unactivated accounts should not be possible.

**Comment by MichaelJCole** [comment]
Hi, I just ran into this.

If the server re-sends the email, the server would be nicer to the user if the server didn't expire previous tickets - otherwise, the user will have recent emails with invalid links.

**Comment by MichaelJCole** [comment]
@elitan @plmercereau Hi there, I need this for my application.  

I took another look from the view of limiting email abuse (e.g. preventing 100000 API calls in an hour).  

From that view, I came up with a partial solution that just changes the behavior of /auth/register

The premise is:
- Only send one email per ticket
- Wait until ticket expires before sending a new ticket+email.
- Send up to 5 mins before expiration to prevent sending a ticket that immediately expires

Benefits:
- user is never completely locked out of registering their email
- configure ticket_expiration to configure rate limit.
- anonymous API is limited to 1 activation-email/unactivated-account per expiration
- doesn't change current schema or api - only adds an env var

If changing the user schema is an option, a better approach might be to 
1) remember how many emails have been sent,
2) set a configurable max of activation-emails / account (e.g. 20).  
3) resend emails any time and set link expiration to a month

I'm learning GraphQL so there's some psuedocode for data queries. What do you think of the approach?  

```
import {
  AUTO_ACTIVATE_NEW_USERS,
  SERVER_URL,
  EMAILS_ENABLE,
  DEFAULT_USER_ROLE,
  DEFAULT_ALLOWED_USER_ROLES,
  VERIFY_EMAILS,
  VERIFY_EMAILS_EXPIRES_MINUTES // Should be > 5 mins
} from '@shared/config'
import { Request, Response } from 'express'
import { asyncWrapper, checkHibp, hashPassword, selectAccount } from '@shared/helpers'

import Boom from '@hapi/boom'
import { emailClient } from '@shared/email'
import { insertAccount } from '@shared/queries'
import { registerSchema } from '@shared/validation'
import { request } from '@shared/request'
import { v4 as uuidv4 } from 'uuid'
import { InsertAccountData } from '@shared/types'

async function registerAccount({ body }: Request, res: Response): Promise<unknown> {
  const { email, password, user_data = {} } = await registerSchema.validateAsync(body)
  const account = await selectAccount(body)

  // Used in sending email below.  Declared here to hoist scope out of else clause of next if statement
  const now = new Date()
  const ticket = uuidv4()
  const ticket_expires_at = new Date()
  ticket_expires_at.setTime(now.getTime() + VERIFY_EMAILS_EXPIRES_MINUTES * 60 * 1000) // active for 60 minutes
  const password_hash = await hashPassword(password)

  if (account) {
    const { current_ticket_expires_at, active } = await account.getData()

    // Already active, cancel this request
    if (active) {
      throw Boom.badRequest('Account already active.')
    }

    // If not verifying emails, cancel this request
    if (!VERIFY_EMAILS) {
      throw Boom.badRequest('Account already exists.')
    }

    // Send only one activation email per ticket.
    // If called again before ticket expired, reply error message.
    if ( current_ticket_expires_at.getTime() > now.getTime() - 5*60*1000) {
      throw Boom.badRequest('Please check your spam folder for activation link.')  
    }
    // If called again after ticket expired, new ticket+email
    await account.setData({
      ticket,
      ticket_expires_at,
    })
  } else {
    // Create new account
    await checkHibp(password)

<file continues without modification>
```
