### ISSUE TITLE
Suggestion: Support OpenAPI/swagger spec for API to automatically generate client libraries

### ISSUE THREAD

**Issue by ewhal** [nhost/hasura-backend-plus#240]
OpenAPI annotations allow for standardized generation of API docs which allow use of 
swagger-codegen or similar to automatically generate client libraries in many languages to interface with said API.
Gives people a lot more options over just the regular JS SDK
https://www.npmjs.com/package/express-swagger-generator
https://github.com/swagger-api/swagger-codegen

**Comment by SkinyMonkey** [comment]
I noticed that hapi.js is used for everything but the routes.
Using it would allow to generate the swagger spec from the code instead of having to update it by hand each time a modification of the API occur.

The only pb i see is the compatibility with express js middlewares : morgan, helmet etc...

**Comment by elitan** [comment]
We'll provide client libraries manually. More info under Libraries: https://docs.nhost.io/
