### ISSUE TITLE
No way of setting customer_register_data

### ISSUE THREAD

**Issue by elitan** [nhost/hasura-backend-plus#242]
in `auth.accounts.customer_register_data`.

Instead `REGISTRATION_CUSTOM_FIELDS` is being used to set fields on registration directly on the users table.

**Comment by plmercereau** [comment]
The current behaviour allows the developer to define several columns in the `users` table that can be filled on registration.

If they want to put all the data into one `jsonb` `customer_register_data` column, then they only need to define `REGISTRATION_CUSTOM_FIELDS=customer_register_data`.

That way is more flexible as it can serve both scenarios

**Comment by elitan** [comment]
Ok I'll test that! 👍
