### ISSUE TITLE
User impersonation

### ISSUE THREAD

**Issue by SkinyMonkey** [nhost/hasura-backend-plus#250]
Is there a mecanism to impersonate/"sign in as a user" for support purposes in HBP?

What would it take to do this?

**Comment by elitan** [comment]
No there is not. 

I guess a master password (as env var) would be OK. So on login HBP check if the password is the user's password or the master password.

**Comment by SkinyMonkey** [comment]
The env var would make sense.
But maybe we can copy Hasura's way of doing things : accept a header that if passed and set correctly would allow any action on HBP.

I'll try to implement this later today

**Comment by SkinyMonkey** [comment]
To continue our discord discussion :
In the current implementation, an ADMIN_SECRET env was added, which bypass the password's check at login to get a token.

Questions:
- should this env variable have the same value as HASURA_GRAPHQL_ADMIN_SECRET?
Or should they be two distinct values?
