### ISSUE TITLE
New device

### ISSUE THREAD

**Issue by SkinyMonkey** [nhost/hasura-backend-plus#251]
Tracking devices used for connections and send email in case of a new used device is implemented by big actors and I think it could be a useful feature.

I might need integration from an external service to get informations on the device based on its fingerprint?

**Comment by elitan** [comment]
Something like this could make sense to work with:
https://github.com/yusukeshibata/express-fingerprint

**Comment by srghma** [comment]
agree, the page with all (mobile/tablet) devices listed and the ability to revoke/remove (e.g. lost) device would be a cool addition

**Comment by elitan** [comment]
Let's continue the discussion here: https://github.com/nhost/hasura-backend-plus/issues/133
