### ISSUE TITLE
API should be present as a Remote Schema

### ISSUE THREAD

**Issue by esseswann** [nhost/hasura-backend-plus#256]
API calls should be available as GraphQL mutations rather than a separate REST endpoint
This should include file upload using something like [this](https://github.com/jaydenseric/apollo-upload-client#function-createuploadlink) when Hasura supports non-json requests
This would greatly simplify proxy and frontend setup, as well as some future permission configurations

I can help implementing it

**Comment by elitan** [comment]
The reason why we have HBP as a separate endpoint is that we have better control over the API, we can handle cookies and file upload/download really well.

We have put some deep thoughts into merging it with Hasura's GraphQL API but so far, from our understanding, it's better to keep HBP separated.

If you want to give it a go, I think start with login/refresh/file upload/download first. Those are the "hardest" to get right.

**Comment by esseswann** [comment]
Login\Refresh I've done on a production project, it's not super complicated, since Hasura can pass the HTTP cookie header from remote schema to the frontend.

The upload is a bit of a problem, because Hasura currently does not support multipart graphql requests which is tracked here https://github.com/hasura/graphql-engine/issues/2419 so it's either Base64 hack or we wait for said support

On the download part I think that this is the only endpoint that should be exposed not inside GraphQL. By the way, can you help understaind, does HBP currently support any kind of permission checks on file download?

**Comment by elitan** [comment]
Understood. I think for a transition like this to make sense we should move everything into the GraphQL API. Until then we'll keep it as is. We try to make it easy to use HBP with our [JS SDK](https://github.com/nhost/nhost-js-sdk) too.

Yes HBP has a very powerful permission check system for files:
https://github.com/nhost/hasura-backend-plus/blob/master/custom/storage-rules/rules.yaml
