### ISSUE TITLE
Cors Issues

### ISSUE THREAD

**Issue by aaronhayes** [nhost/hasura-backend-plus#257]
I've been seeing the following CORS issue a bit; using a CRA running outside of docker.

`Access to XMLHttpRequest at 'http://localhost:8081/auth/token/refresh' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

It is only considered to be the same origin if the protcol, host and port are the same.

**Comment by elitan** [comment]
From my understanding, this should not be an issue given this:

https://github.com/nhost/hasura-backend-plus/blob/master/src/server.ts#L23

**Comment by elitan** [comment]
Make sure it's not a rate-limit issue. I think I encountered this when I tested HBPv2 with CRA. The problem was I was hitting the rate limit, which is like 100 request per 15 min or so by default (we should increase that).

**Comment by aaronhayes** [comment]
Good idea. Will try the rate limits, and report back! 

If that is the issue; it will be worth documenting somewhere, and maybe even increasing the default

**Comment by aaronhayes** [comment]
Yep that seems to be the problem!

1. Decreased `MAX_REQUESTS` to equal `1`. Issue was replicated immediately.
2. Increased `MAX_REQUESTS` to `500` (which is about 30 requests per minute), and haven't seen the issue since.
