### ISSUE TITLE
Invalid password error messages

### ISSUE THREAD

**Issue by aaronhayes** [nhost/hasura-backend-plus#270]
I think the server should return a standard message regardless of which "step" has failed within the Authentication process. The reasoning is we don't want to give any extra information to potential hackers. Giving back:
1. "invalid password" 
2. "password" length must be at least 5 characters long
3. Account does not exist.

All give potential information that can narrow down their attack.

My suggestion is HBP returns a simple:
"Invalid username or password".

**Comment by aaronhayes** [comment]
That being said you could always try to register with an email address to see if the account exists. Regardless, I think it makes sense to return a standard message. Happy to discuss.

**Comment by elitan** [comment]
This approach has it's pros and cons. Could we gather some data on some big sites and see how they handle this?

Or maybe we could use an env var to control this.

`AUTH_DETAILED_PUBLIC_ERROR_MESSAGES (boolean)`

**Comment by elitan** [comment]
> My suggestion is HBP returns a simple:
> "Invalid username or password".

I agree.

**Comment by alaister** [comment]
I think the downside of UX is far greater than the security concern here. I'd much rather tell the user that the account does not exist than have them trying to guess which the incorrect field is.

I think if you do want to go down this route, an env var is the way to go!

**Comment by elitan** [comment]
Should always return if login fails: 

`Invalid email or password`

**Comment by nunopato** [comment]
for reference, the message for registration was changed here: https://github.com/nhost/hasura-backend-plus/commit/c9cf3937404afd7ff973e589ef2e4ee1e9b1c0cc

**Comment by komninoschat** [comment]
For login, only use the following error message: "Invalid email or password" and for magic link: "Invalid email".
