### ISSUE TITLE
Multistage docker build

### ISSUE THREAD

**Issue by elitan** [nhost/hasura-backend-plus#274]
No need to keep .ts files in production docker image for example.

**Comment by plmercereau** [comment]
True.
Now that HBP runs on node, and not ts-node anymore, all the packages related to typescript e.g. @types/xyz should be move from dependencies to devDependencies in the package.json file.

Stages would be:

1. install all the required packages for transpiling the app
2. transpile/build from ts to js
3. new stage: install only the production packages
4. copy the dist directory created in step 2
