### ISSUE TITLE
What are the storage routes?

### ISSUE THREAD

**Issue by MarcelloTheArcane** [nhost/hasura-backend-plus#279]
I'm trying to get the access token from a file in the min.io storage, but I can't seem to find the route or authorisation requirements within the repository anywhere.

It looks like routes are in a custom yaml file:

https://github.com/nhost/hasura-backend-plus/blob/1dba79ec27e5ae3948bad264a19ad4db39e85ee1/src/routes/storage/utils.ts#L53-L63

I've found this in the tests, but it doesn't appear to be valid in my nhost.io repository.

https://github.com/nhost/hasura-backend-plus/blob/1dba79ec27e5ae3948bad264a19ad4db39e85ee1/src/routes/storage/storage.test.ts#L101-L110

Is there anywhere I can find a list of all the storage route URLs ?

**Comment by elitan** [comment]
You are right, it's a custom storage rules.yaml file. Look here: https://github.com/nhost/hasura-backend-plus/tree/master/custom/storage-rules

**Comment by MarcelloTheArcane** [comment]
Is there any way to get the token again? I can't see the right path...

**Comment by elitan** [comment]
Yes through `/storage/m/your-path/file.png`. The token should be present in the metadata. Make sure you have `read` access on the path.
