### ISSUE TITLE
Get user data?

### ISSUE THREAD

**Issue by MarcelloTheArcane** [nhost/hasura-backend-plus#290]
I'm looking at these [docs on authentication](https://github.com/nhost/hasura-backend-plus/blob/b57acdde7f55ab5d219cba6d824a3b48d665240d/docs/api.md), but I can't find any way of getting the user data.

In HBPv1, it used to be `/auth/user`.

**Comment by elitan** [comment]
We don't have such an endpoint. But maybe we should add it to HBPv2 too?

I remember we added `/auth/user` to HBPv1 for some NuxtJS specific thing? What kind of information did we include there?

**Comment by MarcelloTheArcane** [comment]
Yep that's right, [the Nuxt auth module](https://auth.nuxtjs.org) needs to get user data apparently.

Returning the row from the `public.users` table, and any account roles would return everything I need I think.

**Comment by plmercereau** [comment]
I think it depends on the purpose of getting this data.

If it's related to authentication/authorization (which is the case of this nuxt module), all the required information is supposed to be in the JWT. So I would rather try to use the JWT endpoint and transform the claims in the frontend through the `transformResponse` of axios' [request config](https://github.com/axios/axios#request-config).

On a general standpoint, If it's more related to the app, the best way to proceed is to go through regular GraphQL operations through the Hasura endpoint

**Comment by MarcelloTheArcane** [comment]
@plmercereau I've done that, thanks for the suggestion!
