### ISSUE TITLE
reduce the docker image size

### ISSUE THREAD

**Issue by plmercereau** [nhost/hasura-backend-plus#291]
Related to #274 

The current docker image size is 617MB (!!!)

As discussed in the past we should find ways to reduce it. What we could do:

- multi-staged docker (#274)
- split devDependencies/dependencies
- identify possible unused packages
- find a replacement to aws-sdk
- ...

Any idea is welcome!

**Comment by plmercereau** [comment]
`yarn cache clean`: -337MB
:flushed: :flushed: :flushed: :flushed:

**Comment by elitan** [comment]
wow, how does that work?

**Comment by plmercereau** [comment]
Yarns put its cache to `/usr/local/share/.cache/yarn`. I browsed a bit the files in the docker and found out this directory was huge. I guess the directory won't be the same if commands are ran with another user than root.
Eventually the docker image size is almost divided by 3 (taking into account all the typescript/dev-related packages that have been moved aside in devDependencies)

**Comment by plmercereau** [comment]
We still have a 216MB docker image. That's an improvement but I think we can find ways to reduce its size.
When going inside a container the `node_modules` directory is still 131.4M, to find a replacement to `aws-sdk` will make a real change (-50MB)

**Comment by elitan** [comment]
We only use s3 for a few calls. Maybe we could replace them with axios?

https://github.com/nhost/hasura-backend-plus/blob/master/src/routes/storage/upload.ts#L45
https://github.com/nhost/hasura-backend-plus/blob/master/src/routes/storage/get.ts#L33

etc

**Comment by plmercereau** [comment]
Yes, or something like this:
https://www.npmjs.com/package/aws-s3

**Comment by plmercereau** [comment]
There's also:
https://docs.min.io/docs/javascript-client-quickstart-guide

**Comment by elitan** [comment]
![image](https://user-images.githubusercontent.com/331818/88477632-03658f00-cf42-11ea-8f06-dd9e79d6e678.png)

And the `minio` seems to have all methods we need: https://docs.min.io/docs/javascript-client-api-reference

I think we should use `minio` instead of `aws-sdk`.

**Comment by praneybehl** [comment]
minio-js sdk will be much lighter compared to the aws-sdk.
https://github.com/minio/minio-js

**Comment by elitan** [comment]
Left to do:

- split devDependencies/dependencies
- identify possible unused packages
- find a replacement to aws-sdk (see comments above)
