### ISSUE TITLE
Add SameSite=None to refresh token cookies

### ISSUE THREAD

**Issue by MarcelloTheArcane** [nhost/hasura-backend-plus#293]
When I use the refresh tokens on my domain, I get this warning:

> A cookie associated with a cross-site resource at `http://backend-<repo>.nhost.app/` was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

I think this will go away if `SameSite=None` is explicitly set on the cookies.

**Comment by at74S6v** [comment]
This is not enough apparently. `SameSite=None` without `Secure: true` will be rejected by Chrome according to this [feature](https://www.chromestatus.com/feature/5633521622188032) page. 
Cookies are rejected on the lastest docker image with #294, we need `Secure ` attribute!

**Comment by elitan** [comment]
Yep, we need to use `SameSite=None` and `Secure` together.

The problem with this is with local development because usually, a developer won't have HBP running with https locally. If the cookie is sent with `Secure` on an insecure (non-https) connection the cookie will be rejected by the browser.

Maybe we should set different cookie props depending on the environment:

**Locally**

```
SameSite: lax
Secure: false
```

This will work since both HBP and the frontend will use `localhost` as a domain (same site).

** Preview and Production **

```
SameSite: none
Secure: true
```

**Comment by elitan** [comment]
However, given [Chrome is planning to phase out third-party cookies](https://blog.chromium.org/2020/01/building-more-private-web-path-towards.html) we might as well start using the `SameSite: lax` as default.

**Comment by elitan** [comment]
After some discussion with @plmercereau we think this is the best way forward:

Add two env vars:

- `COOKIE_SECURE` : boolean. Defaults to false
- `COOKIE_SAME_SITE` : [strict, lex, none]. Defaults to lex.

Communicate clearly that HBP and the app's frontend should be on the same domain for HBP to work ideal.

**Comment by MarcelloTheArcane** [comment]
@elitan what does this mean for nhost, if it needs to be on the same domain ideally?

**Comment by elitan** [comment]
@MarcelloTheArcane That you should set a CNAME for your subdomain (ex. backend.example.com) to point to the backend domain at Nhost.

You can already do this in **Settings -> DNS**.
