### ISSUE TITLE
File with spaces in the name can't be returned

### ISSUE THREAD

**Issue by MarcelloTheArcane** [nhost/hasura-backend-plus#295]
I've uploaded a file through console.nhost.io, with spaces in the name. When the URL gets sent, it changes special characters (like spaces) into URL-encoded ones.

This means that my file with spaces can't be found, but when I changed it to use underscores instead of spaces, it was fine.

I think you need to run `decodeURIComponent(<file name>)` on the files first before.

**Comment by elitan** [comment]
This was a local issue in the Nhost Console. It's fixed now using `decodeURIComponent`. I recommend everyone to remove spaces in files and folders when uploading files to HBP.
