### ISSUE TITLE
SPA Session Support

### ISSUE THREAD

**Issue by ConProgramming** [nhost/hasura-backend-plus#303]
Would there be any way to connect this up to my SPA with sessions instead of having to just use a JWT?

**Comment by elitan** [comment]
I'm not sure how that would work? since we want to send the JWT token to the Hasura GraphQL endpoint.

**Comment by ConProgramming** [comment]
Hasura itself works with sessions doesn't it? https://hasura.io/docs/1.0/graphql/manual/auth/index.html

**Comment by elitan** [comment]
Hasura support [JWT token](https://hasura.io/docs/1.0/graphql/manual/auth/authentication/jwt.html) or authenticate using a [webhook](https://hasura.io/docs/1.0/graphql/manual/auth/authentication/webhook.html).

HBP uses a JWT token approach.

Maybe if you describe your use-case and issues you have with the current approach, and we can see if using a webhook is something we should implement.

**Comment by ConProgramming** [comment]
Ah okay that makes sense.

Currently we're looking for the best auth system to use with Hasura, and will likely end up having to spin up something custom with Keycloak or Ory. I'd love to use HBP, but I think we need the security of using webhooks/sessions in a SPA running on node.

Implementing webhooks with HBP would be greatly preferred though! I love y'alls storage with Minio and easy authentication setup with roles etc. in Hasura.

**Comment by elitan** [comment]
Just to get a better understanding, what is it with a webhook that you prefer over JWT tokens? Could you elaborate a bit on the limitations you have with the current setup?

**Comment by elitan** [comment]
I'll close this for now.

HBP works well with SPA's. Especially with `[nhost-js-sdk](https://github.com/nhost/nhost-js-sdk)`.
