### ISSUE TITLE
How authenticate a user with a specific role in runtime

### ISSUE THREAD

**Issue by sytabaresa** [nhost/hasura-backend-plus#305]
Hi, I am trying to authenticate a user with multiple assigned roles, but when I use the login endpoint, It only responses with a JWT token with `x-hasura-default-role` and `x-hasura-allowed-roles` claims. when I use this JWT token with role-based permissions in Hasura, Hasura only recognize the `x-hasura-default-role` as the only one role, despite the array of allowed roles. and doesn't authorize none of the other list of roles (I don't know if only happens in bulk queries or normal queries too). There is a way to *login* with HBP and specify the role that I want? I have multiple login forms to every role/organization that I have, and I want to use the specific form to assign in runtime what role to use (one of the assigned roles of that user). I understand that `x-hasura-role` *can be used* to do that, but I don't know how to add in runtime to the `/auth/login` response.

Thanks in advance  for your attention.

**Comment by elitan** [comment]
When sending your GraphQL request you can add an `x-hasura-role` header that you want to use for that specific request. The role (`x-hasura-role`) you set must be present in the array of `x-hasura-allowed-roles`.

Let's say you have:
```
x-hasura-default-role: user
x-hasura-roles: ['user', 'editor']
```

and you want to make a request as a `editor`:

```jsx
const { loading, error, data } = useQuery(MY_QUERY, {
    context: {
        headers: {
            "x-hasura-role": "editor",
        }
    }
})
```
