### ISSUE TITLE
Load mounted resources externally

### ISSUE THREAD

**Issue by elitan** [nhost/hasura-backend-plus#323]
Load mounted resources (email templates and storage security rules) externally.

The idea is to avoid mounting files from the host into the container.

So, as an alternative, HBP could load these resources (email templates, rules) externally on startup from an URL, ex:

`RESOURCE_URL = https://example.com/hbp-resources`

We'll then set a protocol for what resources should be where, so ex email templates should be available on:

```
/emails/activate-account/subject
/emails/activate-account/text
/emails/activate-account/html
... etc
/storage-rules/rules.yaml
```

**Comment by plmercereau** [comment]
I personally won't load HBP that way as it creates another dependency to an external service, hence creates another point of failure.

I solved the problem in building a two lines custom docker file e.g.
```
FROM nhost/hasura-backend-plus:latest
COPY storage-rules.yaml /app/custom/storage-rules/rules.yaml
```

**Comment by elitan** [comment]
This will not deprecate the current way, it's just a new additional way.

This is specific for Nhost and for us to scale HBP to our customers, and it won't affect the current way of mounting email templates and rules.

Security-wise I agree. We should probably add a token that should be sent along as a query parameter for authorization.

**Comment by plmercereau** [comment]
Well good luck with that then 😊

File sync can be tricky and I'm not sure http would be the best fit, in my experience it ends up in some spaghetti code. Small example: what happens if one of the file changes?

There's plenty of tools that can be added to the container e.g. Cron+rsync+SSH, syncthing etc

**Comment by elitan** [comment]
I'm thinking something along the lines of:

```
@startup:

if fileExist(email-template):
  return; # file already exist, was probably mounted
else:
  // for subject,text,email (+ rules)
  const text = getFile(external_url + `/emails/activate-account/text?token=<token>`)
  saveFile(/app/custom/email/actiave-account/text, text);
```

Internally we'll restart the auth container once a file (email/rule) is changed on Nhost.

**Comment by plmercereau** [comment]
I would condition the download to the existence of an external URL env var rather than the existence of files, as defaults would exist. And IMHO defaults should be included as hbp should work out of the box i.e. without mounting of fetching anything outside of the container

**Comment by elitan** [comment]
True! That's better!

```
if process.env.RESOURCE_URL.exists():
  // for subject,text,email (+ rules)
  const text = getFile(process.env.RESOURCE_URL + `/emails/activate-account/text?token=<token>`)
  saveFile(/app/custom/email/actiave-account/text, text);
```

**Comment by elitan** [comment]
We’ve decided to only fix bugs and refactors on Hasura Backend Plus from now on because we’re working on a new auth + storage service for Hasura. Currently, these new repositories are private but will be open-sourced soon. 

We’ll have your issue in mind when developing the new services. So thanks for filing this issue

 This means I’ll close this issue for now.
