### ISSUE TITLE
Unsigned cookie with user-id is enough for deleting an account

### ISSUE THREAD

**Issue by jlvdh** [nhost/hasura-backend-plus#334]
Hi there,

I'd like to open up a discussion regarding the authentication middleware:

When run without a COOKIE_SECRET environment variable, unsigned cookies are used for authentication:

https://github.com/nhost/hasura-backend-plus/blob/master/src/middlewares/auth.ts

Subsequently I can use an unsigned cookie with just the user_id to delete a user and it passes the `if (!req.permission_variables)`

https://github.com/nhost/hasura-backend-plus/blob/master/src/routes/auth/delete.ts#L10

- Why is it necessary to have a permission_variables cookie?
- Why is there a need to use the permission_variables cookie for authentication on top of the JWT?
- When the cookies are signed would this be considered secure enough?

Just a few questions I have, otherwise really like the project 👍

**Comment by elitan** [comment]
>Why is it necessary to have a permission_variables cookie?

The `permission_variables` cookie is used for mainly two things

1. Resolve permissoins on GET request for files (storage)
2. Removes the need of passing `refresh_token` as a query-parameter during login/signup processes.

However, my recommendation is to not use the cookies at all.

> Why is there a need to use the permission_variables cookie for authentication on top of the JWT?

See above. Again. It's 100% fine to not use cookies (I don't in my projects and we don't use it at Nhost).

> When the cookies are signed would this be considered secure enough?

Yes. Maybe we should do the `COOKIE_SECRET` env var mandatory?

**Comment by komninoschat** [comment]
See #505.
