### ISSUE TITLE
How to handle duplicate email registrations from different providers

### ISSUE THREAD

**Issue by elitan** [nhost/hasura-backend-plus#335]
Issue:

1. register using Google
2. register using Github with same email

problem:
`Error: Uniqueness violation. duplicate key value violates unique constraint "accounts_email_key":`

Merge accounts?

**Comment by janakact** [comment]
Has to merge it. Will it work if we only add the record into `account_providers` table instead, if there is a unique key violation in `accounts` table?

**Comment by elitan** [comment]
@janakact That's the exact solution I was thinking of too.

We should use a GraphQL [upsert](https://hasura.io/docs/1.0/graphql/core/mutations/upsert.html) to handle this.

If you could do a PR for this that would be fantastic!

**Comment by janakact** [comment]
I created a pull request. (Not so sure about it). I will let you know once I test it. 
#339

**Comment by janakact** [comment]
@elitan Hi, Is there a partifular way to set this up for development. ? 
When I run `./start.sh dev` it seems like an `.env.development` file is missing. Is it okay if I copy from the sample and create one ?

**Comment by plmercereau** [comment]
You would rather create the file from the [.env.ci](https://github.com/nhost/hasura-backend-plus/blob/master/.env.ci) file as a starter - it is configured to work with docker-compose. fyi `./start.sh dev` also embeds a mailhog mock email server

**Comment by janakact** [comment]
@plmercereau Thanks. Worked as a charm. <3 
@elitan updated the pull request, ready to review.. Let me know if there's anything to be done :smile:

**Comment by elitan** [comment]
Great. Yea let's continue this discussion in the PR.
