### ISSUE TITLE
There is no documentation for enabling OAuth Provider like Google, Facebook etc.

### ISSUE THREAD

**Issue by danny2310** [nhost/hasura-backend-plus#349]
I checked the Github page and documentation on the website. But could not find a way to enable google auth.

**Comment by SkinyMonkey** [comment]
In the meanwhile, by reading the code in src/auth/providers and read the passport js documentation you should be able to understand how it's done.

Hints:
Set HBP+ env variables like this:
PROVIDER_SUCCESS_REDIRECT, PROVIDER_FAILURE_REDIRECT: link where the user will be redirected in your frontend if the operation works/fail (example : http://localhost:8000/oauth/success)

and example for facebook:
FACEBOOK_ENABLE: "true"
FACEBOOK_CLIENT_ID: ${YOUR_APP_ID} // you'll find in on facebook developpers page
FACEBOOK_CLIENT_SECRET: ${YOUR_APP_SECRET} // idem

**Comment by diogoeichert** [comment]
Thanks, @SkinyMonkey. I think the [OAuth Providers](https://github.com/nhost/hasura-backend-plus/blob/master/.env.example#L114) section from `.env.example` might be useful to subscribers of this issue as well.
