### ISSUE TITLE
Google OAuth - callback request is not resolving

### ISSUE THREAD

**Issue by shashankrepo** [nhost/hasura-backend-plus#350]
When I send a get request to HBP google provider, it redirects to google sign in but when I login to the google account, the callback to HBP is pending and the request is not resolving.

I set the following env variables

```
GOOGLE_ENABLE=true
GOOGLE_CLIENT_ID=xxx
GOOGLE_CLIENT_SECRET=xxx
PROVIDER_SUCCESS_REDIRECT=https://localhost:3000
PROVIDER_FAILURE_REDIRECT=https://localhost:3000/error
```

HBP log:

<img width="1127" alt="Screen Shot 2020-10-20 at 8 44 43 pm" src="https://user-images.githubusercontent.com/13571499/96578422-85364000-1318-11eb-97cb-7c01571ce972.png">

Chrome dev tool network:

![image](https://user-images.githubusercontent.com/13571499/96578661-e5c57d00-1318-11eb-81b3-2228c9e809f5.png)

**Comment by elitan** [comment]
We resolved the issue via Discord. The problem was @shashankrepo was using HBPv1 schema (with `usersname`). Upgrading to the HBPv2 schema resolved the issue.
