### ISSUE TITLE
Storing refresh token in local storage is not safe

### ISSUE THREAD

**Issue by srghma** [nhost/hasura-backend-plus#352]
1. in examples, you write that it's better to store in `localStorage`

but it's not true

https://github.com/hasura/graphql-engine/issues/2205

2.

I would also argue that storing access_token in memory is not 100% (maybe, it's based on how you add it to a header)

because

suppose our site was XSSed - malicious user could find how to sniff your token

```js
// your code

let jwtAccessTokenRef = null

axios.useHeader(() => { Authentication: `Basic ${jwtAccessTokenRef}` })

// xss injected code

const oldHeaderCreator = axios.SOMEHOW

axios.useHeader(() => {
  const oldHeader = oldHeaderCreator()
  send(oldHeader)
  return oldHeader
})

```

maybe it's better to use httpOnly for `access_header` too?

**Comment by elitan** [comment]
HBP (hasura-backend-plus) does not specify where you store your tokens. You can store them wherever you like.

if by `access_token` you mean JWT token then where do you suggest it's stored? The token must be sent with subsequent GraphQL requests.

Does Hasura allow the JWT token to be sent as a httpOnly token?

**Comment by elitan** [comment]
Closing for now. You can use HBP to store tokens using cookies or on the client (wherever you like).
