### ISSUE TITLE
Redirect on account confirmed

### ISSUE THREAD

**Issue by elitan** [nhost/hasura-backend-plus#354]
Instead of: 
![image](https://user-images.githubusercontent.com/331818/97914229-dcdc9e80-1d4f-11eb-8ada-8af1b1d7d7ef.png)

**Comment by MichaelJCole** [comment]
Hey there, I'd like "activate" to work like this:

1) Set the auth cookies in response
2) 308 to a custom URL specified using an ENV var.  E.g. 
```
ACTIVATE_REDIRECT_URL=https://some.com/www/index.html?token={{jwt_token}}
```
3) replace {{jwt_token}} with the user's token.

This will allow me to create a front-end that has the user logged in after clicking the link.  There's no need for them to re-enter the password on signup.

**Comment by MichaelJCole** [comment]
@elitan I need this sooner than later.  Would you like a PR for it?
