### ISSUE TITLE
How does backend validate email?  How to make same test on front-end?

### ISSUE THREAD

**Issue by MichaelJCole** [nhost/hasura-backend-plus#370]
Hi, I'm getting email validation errors on the HPB, which is great but unexpected.

I was using a regex to validate - first my own, then [this one from HBP source](https://github.com/nhost/hasura-backend-plus/blob/05b68b3c38a92ed76df8ee4034f2a70c7ee6bf0c/migrations-v1/1589098900001_migrate_v1_v2/up.sql#L36)

[Regexr says "aa@aa.aa" passes validation](https://regexr.com/5g4gh), but HBP server replies:
```
{"statusCode":400,"error":"Bad Request","message":"\"email\" must be a valid email"}
```

On the server console, I'm seeing:
```
OPTIONS /auth/register 204 0 - 0.145 ms
[Error [ValidationError]: "email" must be a valid email] {
  _original: { email: 'aa@aa.aa', password: 'xxxxxxxx' },
  details: [
    {
      message: '"email" must be a valid email',
      path: [Array],
      type: 'string.email',
      context: [Object]
    }
  ]
}
POST /auth/register 400 84 - 1.395 ms
```

How does the server test to determine this?  Thank you!

**Comment by aaronhayes** [comment]
The backend uses [https://github.com/sideway/joi](Joi) to validate emails. 
You can see the code here https://github.com/nhost/hasura-backend-plus/blob/master/src/shared/validation.ts#L41
