### ISSUE TITLE
Ability to Add a FRONTEND_URL That Can be Used in Email Templates

### ISSUE THREAD

**Issue by zicklag** [nhost/hasura-backend-plus#373]
Hey there! I'm loving this and it is working really great for my app so far, so thanks!

When setting up my app I realized that I needed the ability to set a `FRONTEND_URL` environment variable that will be added to the locals during email template substitution. This is required if you don't use a reverse proxy to host hasura, your frontend, and HBP all under the same server URL because when implementing the "forgot my password" workflow, I don't actually have the URL of the frontend so that I can redirect to it, I only have the URL of the HBP server, which is set in the `SERVER_URL` variable.

Maybe the correct solution is just to use a reverse proxy? I don't know, but during development at least a reverse proxy was less than convenient to setup when I could otherwise just set the URL environment variable. Not sure 100% how I feel about it so I'm open to just not changing anything and mentioning the situation in the documentation somewhere maybe.

**Comment by zicklag** [comment]
OK, yeah, on another note, I did just find a super easy way to setup the proxying with Webpack so it actually works really nicely now. Still maybe a pointer on that workflow could be good int he docs. I'd still like to hear other thoughts, so I'll leave this open for just a bit.

**Comment by komninoschat** [comment]
Great idea! One minor suggestion would be to use ‘APP_URL’ instead of ‘FRONTEND_URL’, since we also support mobile apps but this is definitely on the top of our list.
