### ISSUE TITLE
Package.json Version Mismatch

### ISSUE THREAD

**Issue by JKing-B16** [nhost/hasura-backend-plus#374]
I was having trouble with the email sending, when I stumbled on an issue with the package.json. GIT was giving me a version v2.2.1 + extra commits, but the package.json was still showing v2.1.0.

I'd suggest using the "npm version [patch|minor|major]" command to implement the GIT tag and update package.json. This could even be expanded with the package.json "preversion": "npm run build" or "npm run test" command to ensure a clean build/test.

This project is great and greatly appreciated.

**Comment by JKing-B16** [comment]
One more comment on this, would be that it would be great if there was a path that could be called to verify the compiled version. Something like /auth/version or /auth/v. This would greatly help in debugging potential installation issues.

**Comment by elitan** [comment]
The [`package.json`](https://github.com/nhost/hasura-backend-plus/blob/master/package.json#L8) should match the [latest release](https://github.com/nhost/hasura-backend-plus/releases) now.

You can access the version at `/version`:

```json
{"version":"v2.2.4"}
```
