### ISSUE TITLE
Email Templates

### ISSUE THREAD

**Issue by JKing-B16** [nhost/hasura-backend-plus#375]
I've seen some places in the documentation mentioning email templates, but it would be greatly helpful to have some explicit documentation on how to set that up with docker and the variables/format that the templates can take.

**Comment by beebase** [comment]
I would also like to set up an email template.
Is there any example code or documentation available?

thanks.

**Comment by elitan** [comment]
Sorry, we've been slow on answering here and we'll work on the documentation.

For now, here's some information:

add a volume from your host system to HBP like:

```
    volumes:
      - './custom:/app/custom'
```

**Comment by beebase** [comment]
@elitan  Thanks for the info!

quick question. I'm setting up a "forgot password" page.
Is this method supposed to work? 
(I assume this method sends the user an email with a link to create a new password?)
![image](https://user-images.githubusercontent.com/446089/110626650-4ad31f80-81a1-11eb-8d5b-3e404e6db79c.png)

I'm getting this error:
` Uncaught TypeError: auth.requestPasswordChange is not a function`

**Comment by elitan** [comment]
Can you open a separate issue about this [here](https://github.com/nhost/nhost-js-sdk/issues/new)?

**Comment by beebase** [comment]
done.
https://github.com/nhost/nhost-js-sdk/issues/63

**Comment by komninoschat** [comment]
See #426.
