### ISSUE TITLE
Add Steam as strategy

### ISSUE THREAD

**Issue by elitan** [nhost/hasura-backend-plus#377]
http://www.passportjs.org/packages/passport-steam/

**Comment by komninoschat** [comment]
Steam does not provide the user's email via Open ID which is a problem as the email is required for user registration.

Two possible solutions would be:
- Add another step to the sign up flow where the user has to enter his email (will result in an unactivated account).
- Create an anonymous user with the ability to log in with Steam.

**Comment by elitan** [comment]
E-mail is actually not required ([link](https://github.com/nhost/hasura-backend-plus/blob/master/db/migrations/00001_create-initial-tables.sql#L23)) so I'm thinking we could allow users to register with steam even if `email` and `password` will be `NULL` in the `auth.accounts` table.

It's the same with [Strava](https://www.strava.com/). Strava does not provide an email, and it's possible that other strategies also don't provide an email.

**Comment by elitan** [comment]
We’ve decided to only fix bugs and refactors on Hasura Backend Plus from now on because we’re working on a new auth + storage service for Hasura. Currently, these new repositories are private but will be open-sourced soon. 

We’ll have your issue in mind when developing the new services. So thanks for filing this issue

 This means I’ll close this issue for now.
