### ISSUE TITLE
Allow subset of default roles for registration endpoint.

### ISSUE THREAD

**Issue by st3phan** [nhost/hasura-backend-plus#379]
It would be nice to have the registration endpoint accept a parameter that assigns a default role instead of the default `user` role. Something like this:
`auth.register(email, password, { display_name: "Joe Doe" }, 'rolename')`

If this `rolename` does not exist in the `roles` table it will be added.

====== Original idea ====== 

> It would be nice to have the registration endpoint accept a parameter with a subset of the default allowed roles that are defined in the console settings.
> 
> Let's say we have the following default allowed roles defined in the console settings:
> `[1,2,3,4,5]`.
> 
> The registration endpoint would then look like this:
> `auth.register(email, password, { display_name: "Joe Doe" }, [1,2])`
> 
> If no subset is specified all default allowed roles will be assigned to the user.
> 
> Additionally one of the roles in the endpoint parameters could be set as the default role (instead of `user`).

**Comment by elitan** [comment]
I think we got two "issues" here.

1. Register a user with a specific default role. The default role must be part of the default allowed roles.
2. Register a user with a subset of roles from the default roles.

Does this make sense?

**Comment by aaronhayes** [comment]
@elitan That's how I read it as well. I'd propose adding an optional `register_options` object to the register endpoint.  

`await register(email, password, custom_fields, register_options)`

Register options can have `allowed_roles` and `default_roles`. Can be expanded with other options in the futures.

**Comment by elitan** [comment]
Make sense.

But shouldn't `custom_fields` be part of `registration_options`? If we don't think about backwards compatibility?

**Comment by st3phan** [comment]
> But shouldn't `custom_fields` be part of `registration_options`?

If backwards compatibility is not an issue then this is forward compatible I guess ;-)

> The default role must be part of the default allowed roles

The whole reason for this feature request is that it in my use case I only have 2 roles: `freelancer` and `company`.
A user can only have one or the other role. Not both.
So for the `default_role` option the prerequisite of being part of the existing default roles wouldn't work here.

The prerequisite I can think of would maybe be that the `default_role` already exists in the `auth.roles` table. 
But I guess you could also just add it if doesn't already exists.

**Comment by aaronhayes** [comment]
> Make sense.
> 
> 
> 
> But shouldn't `custom_fields` be part of `registration_options`? If we don't think about backwards compatibility?

Yes, if we don't care about introducing breaking changes, that would be the preferred. 

It would be a trivial code change to upgrade if we to go that way. In most cases you would only call the register endpoint from 1 spot per client - web, ios, android, etc.

**Comment by aaronhayes** [comment]
> > The default role must be part of the default allowed roles
> 
> 
> 
> The whole reason for this feature request is that it in my use case I only have 2 roles: `freelancer` and `company`.
> 
> A user can only have one or the other role. Not both.
> 
> So for the `default_role` option the prerequisite of being part of the existing default roles wouldn't work here.

I believe my approach covers this
Under my proposal you would call `register_options` with both `default_roles` and `allowed_roles` for the user. For example
`await register('joe@example.com', 'securepassword', { display_name: 'Joe' }, { allowed_roles: ['freelancer'], default_role: 'freelancer' }`

> 
> 
> 
> The prerequisite I can think of would maybe be that the `default_role` already exists in the `auth.roles` table. 
> 
> But I guess you could also just add it if doesn't already exists.
> 
> 

currently the `default_allowed_roles` must be present in `auth.roles` otherwise errors will occur. I'd probably stick with this approach.

**Comment by st3phan** [comment]
That would cover it yes. Go for it. Would make my dev life easier :)

**Comment by aaronhayes** [comment]
It will be fairly trivial to implement, question is to introduce breaking changes or not? @elitan

**Comment by aaronhayes** [comment]
I should add the breaking changes would only be introduced to `nhost-js-sdk`. 
All the backend changes would be backwards compatible.

**Comment by aaronhayes** [comment]
Haven't tested this but I think this is all required (without introducing breaking changes). Of course `nhost-js-sdk` would have to be updated as well. 

https://github.com/aaronhayes/hasura-backend-plus/commit/e22d7d71f9b4c7118da3fdf17d2f35ad3eb8e1b1

**Comment by elitan** [comment]
https://github.com/nhost/hasura-backend-plus/pull/396

Based on your code @aaronhayes with some checks.

**Comment by aaronhayes** [comment]
Do we need these checks? I think we just need to ensure that the defaultRole is included in the allowedRoles.

```JavaScript
 // check if register_options.default_role is part of DEFAULT_ALLOWED_USER_ROLES
  if ('default_role' in register_options) {
    if (!DEFAULT_ALLOWED_USER_ROLES.includes(register_options.default_role)) {
      throw Boom.badRequest('Default role must be in DEFAULT_ALLOWED_USER_ROLES')
    }
  }

  // check that register_options.allowed_roles overlapp with DEFAULT_ALLOWED_USER_ROLES
  if ('allowed_roles' in register_options) {
    register_options.allowed_roles.forEach((allowedRole: string) => {
      if (!DEFAULT_ALLOWED_USER_ROLES.includes(allowedRole)) {
        throw Boom.badRequest('allowed_roles must overlap with DEFAULT_ALLOWED_USER_ROLES')
      }
    })
  }
```

So we could simplify those checks and handle invalid default configuration as well...

```JavaScript
...

const defaultRole = register_options.default_role ?? DEFAULT_USER_ROLE
const allowedRoles = register_options.allowed_roles ?? DEFAULT_ALLOWED_USER_ROLES

 // check if defaultRole appears is part of allowed roles
if (!allowedRoles.includes(defaultRole)) {
  throw Boom.badRequest('Default role must be in allowed roles');
}

const accountRoles = allowedRoles.map((role: string) => ({ role }))

... 

```


This would handle the error where someone sets the `DEFAULT_ALLOWED_ROLE` to say `bob` when `DEFAULT_ALLOWED_ROLES` is only `steve` and `john`.

**Comment by elitan** [comment]
But what happens with the following settings and registration_options?

```bash
DEFAULT_USER_ROLE=user
DEFAULT_ALLOWED_USER_ROLES=user,me
```

and

```json
{
  register_options: {
    default_role: "admin",
    allowed_roles: ["user", "me", "editor", "admin"]
  }
}
```

**Comment by aaronhayes** [comment]
Don't we? IMO `DEFAULT_ALLOWED_USER_ROLES` should be the roles assigned to users  when `allowed_roles` isn't set in `register_options`. 

The functionality you're describing would be better suited for a new ENV variable `ALLOWED_USER_ROLES`; 
`allowed_roles` and `DEFAULT_ALLOWED_USER_ROLES` must be a subset of `ALLOWED_USER_ROLES`.

```
DEFAULT_USER_ROLE=user
DEFAULT_ALLOWED_USER_ROLES=user,me
ALLOWED_USER_ROLES=user,editor,me
```

```JavaScript
...

const defaultRole = register_options.default_role ?? DEFAULT_USER_ROLE
const allowedRoles = register_options.allowed_roles ?? DEFAULT_ALLOWED_USER_ROLES

 // check if defaultRole appears is part of allowed roles
if (!allowedRoles.includes(defaultRole)) {
  throw Boom.badRequest('Default role must be in allowed roles');
}


// check if allowed roles is a subset of ALLOWED_ROLES
if (!allowedRoles.every(role => ALLOWED_ROLES.includes(role)) {
  throw Boom.badRequest('allowed roles must be a subset of ALLOWED_ROLES');
}


const accountRoles = allowedRoles.map((role: string) => ({ role }))

... 

```


Also is `admin` a valid option? Being a reserved role within hasura having a user with the `admin` role might be problematic? 


Another consideration is how does this work with OAuth registrations/login?

**Comment by elitan** [comment]
Yea I like the idea of the extra env var + your checks.

That way OAuth registrations can use the `DEFAULT_USER_ROLES` + `DEFAULT_ALLOWED_USER_ROLES`.

And we can use the `register_options.allowed_roles` to be a subset of `ALLOWED_USER_ROLES`.

Maybe in the future we could also send a parameter to OAuth registrations with `default_role` and `allowed_roles`. (Similar to https://github.com/nhost/hasura-backend-plus/issues/386)

**Comment by aaronhayes** [comment]
I think adding the new env var is the best option.

**Comment by beepsoft** [comment]
Great to see this issue! I was struggling myself as well how to add new roles to HBP, but I'm not sure if this issue actually covers it.

My problem is that role assignment should be somehow hierarchical. For example, a user may register itself as `user` but for someone to become an `editor` or register a new `editor` someone with `admin` rights should only be allowed to do that. A user should not be allowed to register itself as `editor`. 

Will this proposal somehow cover this case?

**Comment by aaronhayes** [comment]
@beepsoft 

I just want to clarify - do all your users register as `user`? Then after the registration some users would be upgrade via some mechanism could be upgraded to `editor`? 

> A user should not be allowed to register itself as editor.

Under the proposal (and how #396 implements it) if you were to set the follow env variables:
```
DEFAULT_USER_ROLE=user
DEFAULT_ALLOWED_USER_ROLES=user
ALLOWED_USER_ROLES=user
```

This would prevent users registering as `editor`. Setting users to `editor` would have to be done outside of the registration process. 

These env variables only control what the roles are during the registration process.  There's actually no restrictions on what roles you can set on the `auth.account_roles` table or on the `auth.accounts.default_role` field manually; the role would just have to be present within the `auth.roles` table.

**Comment by beepsoft** [comment]
> @beepsoft
> 
> I just want to clarify - do all your users register as `user`? Then after the registration some users would be upgrade via some mechanism could be upgraded to `editor`?

Yes, this is one use case: one registers as user and then his account is upgraded by an admin.

Another use case would be that an admin can create a new account with `editor` role.

This issue does not support these, I now understand, but is there a way to achieve this?

**Comment by elitan** [comment]
> > @beepsoft
> Yes, this is one use case: one registers as user and then his account is upgraded by an admin.

Not out of the box with HBP.

You'd have to create a serverless function to do that and then hook it up via ex an Hasura Action.

https://docs.nhost.io/custom-api

> > @beepsoft
> Another use case would be that an admin can create a new account with `editor` role for a new user.
> 
> This issue does not support these, I now understand, but is there a way to achieve this?

No. But could be part of an implementation like https://github.com/nhost/hasura-backend-plus/issues/250 where you can override env vars if you're admin.

**Comment by beepsoft** [comment]
> > > @beepsoft
> > > Yes, this is one use case: one registers as user and then his account is upgraded by an admin.
> 
> Not out of the box with HBP.
> 
> You'd have to create a serverless function to do that and then hook it up via ex a Hasura Action.
> 
> https://docs.nhost.io/custom-api

@elitan, thanks, this sounds promising, but what should/could my action do? Should I directly work with the `auth.*` tables (via the exposed hasura API, eg. `update_auth_roles`) to add/update the roles of the target user?

**Comment by elitan** [comment]
yep good question.

I would not recommend interacting directly with tha `auth.*` tables. But you could if you're comfortable with it.

My idea was that you could (in the future) use the `/register` endpoint together with ex `x-hasura-admin-secret to override stuff.

**Comment by beepsoft** [comment]
Yes, the use `x-hasura-admin` for "super admin" stuff would be the most useful, I agree.

Until then, I'm OK with using the `auth` related Hasura API, hope it not changes too much in the future. :-)

**Comment by elitan** [comment]
Yes.

I'm thinking we could use `x-admin-secret` (which would be the same value as `x-hasura-admin-secret`) for HBP.

`x-admin-secret` could be used to both override registration options (and other Auth functions) and interact with Storage with admin privileges.
