### ISSUE TITLE
CSRF protection ?

### ISSUE THREAD

**Issue by b3j0f** [nhost/hasura-backend-plus#382]
I saw helmet in server starting file but no csrf protection like https://www.npmjs.com/package/csurf

Have you protect HBP from csrf by another way ?

**Comment by elitan** [comment]
No it's not and if you're not using HBP with cookies I don't think it's a problem with CSRF. Am I right?

https://stackoverflow.com/questions/52597085/is-firebase-auths-local-persisted-auth-state-secure-and-safe-from-xss-and-csr

https://stackoverflow.com/questions/48505572/csrf-protection-with-firebase-email-password-authentication/48507846

**Comment by komninoschat** [comment]
Our API endpoints use `Content-Type: application/json` which is not vulnerable to CSRF, more on that [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#simple_requests).
