### ISSUE TITLE
[question] Is it possible to migrate an existing users table to DBP? 

### ISSUE THREAD

**Issue by beebase** [nhost/hasura-backend-plus#384]
I suppose this would work:
1. let user sign in with old system
2.  check if user has HBP account
3. if not, auth.register(..)
4. copy original user info into an archive table
5. delete original user record
5. copy user info from archive table into the new user record created by HBP (including pk!)

hm, of course I would also have to update accounts.user_id

**Comment by elitan** [comment]
Yes I think you could do that with a Hasura event trigger on `insert` on the `users` table.

The event trigger would do step 4,5,6.
