### ISSUE TITLE
Is there a way to dynamically pass a redirect_url to an auth provider?

### ISSUE THREAD

**Issue by yannickglt** [nhost/hasura-backend-plus#386]
As we have several frontends with different domains and only one hasura-backend-plus instance, we have different redirect URL depending on the calling frontend app. 

Would there be a way to dynamically pass a redirect_url to an auth provider if given, and fallback to the standard environment variable `PROVIDER_SUCCESS_REDIRECT` otherwise?

Example: //hasura-backend-plus/auth/providers/google?redirect_url_success=http://my-front-end-1/home

**Comment by elitan** [comment]
Yea I think that would be possible. I thik we would have to use the `state` query variable for this.

**Comment by yannickglt** [comment]
`state` sounds to contain the `redirectUrl`, but `hasura-backend-plus` must be in charge of extracting the `redirectUrl` from the `state` in order to redirect to the expected frontend right?

**Comment by yannickglt** [comment]
What is your thought about my last question? 

Maybe it's possible to build the `state` query param from the front-end and sent it to `hasura-backend-plus` (eg: `//hasura-backend-plus/auth/providers/google?state={"redirectUrl":"http://my-front-end-1/home"}`). 
HBP would be in charge of appending the `state` query param to the redirect URL passed to Auth providers (like Google) if present.

Does the second solution look more like your initial idea?

Thanks

**Comment by elitan** [comment]
Yes that's what I was thinking too.

We should also use state to verify the request (not inside this issues scope).

**Comment by yannickglt** [comment]
OK 🙂 

If it's OK to you, I can try to make a pull request to add this behavior of forwarding the `state` query parameter in `hasura-backend-plus`. 
As you mentioned it, such a `state` param could contain a hash to avoid CSRF attacks. It should be straightforward once the param handled by HBP.

**Comment by elitan** [comment]
Go for it! 👍

**Comment by komninoschat** [comment]
Besides `state`, there is also a `redirect_uri` parameter we could use.
