### ISSUE TITLE
File Permissions With a GraphQL Query, Similar To Hasura

### ISSUE THREAD

**Issue by zicklag** [nhost/hasura-backend-plus#387]
Hey there, I was trying to come up with a way to represent the permissions that I wanted on my file uploads for a simple blog scenario, but I couldn't come up with a way to say "allow read/list/write access to the files for this folder if the user is the owner of the blog post corresponding to the folder name".

Essentially, knowing the user role is not enough to control access because I need to know whether or not the user owns the folder. Also, I can't just name the folder off of the user because the owner of a blog post could be changed, and then I would have to move the uploads which is undesirable.

I was thinking it would be great if we could specify the permissions to files similar to how we specify permissions in Hasura, where we give it a query to determine whether or not the user can access a particular item. For instance in this case it would be something like

```gql
query WriteAccess($folder: uuid, $user_id: uuid) {
  posts(where: { id: { _eq: $folder }, primary_author: { _eq: $user_id } })
}
```

So I guess that if the query returned something other than an empty array access would be considered granted? Anyway, not sure what the best way to do it is, but that gets the idea across.

**Comment by zicklag** [comment]
I just implemented something that satisfies my requirements for advanced permissions similar to hasura: [Hasura Upload Manager](https://github.com/katharostech/hasura_upload-manager). it comes at the extra expense of the latency required to make a query to hasura for every file download, but I think that should be minimal and worth it. The project README explains how it works, and it weighs only 340 lines of code!

**Comment by elitan** [comment]
Valid concern. We don't support such a permission system that relies on querying the database.
