### ISSUE TITLE
How can I change a user role from "user" to "admin"?

### ISSUE THREAD

**Issue by beebase** [nhost/hasura-backend-plus#388]
Is this the correct workflow for linking users to roles?

**1. Define roles and set up permissions for the public tables**
![chrome_1BGGdlCxRl](https://user-images.githubusercontent.com/446089/103077966-253a6f00-45d1-11eb-82b8-f4c2d90f8014.png)

**2. map roles defined in public tables to roles defined in auth.roles**
![chrome_KPM1zJ5gpY](https://user-images.githubusercontent.com/446089/103078035-48fdb500-45d1-11eb-837e-c41b40a45535.png)

**3. add or remove roles for users in auth.account_roles table**
![chrome_IxFgu2M0gO](https://user-images.githubusercontent.com/446089/103078174-99751280-45d1-11eb-8467-d804e0836b52.png)

**Comment by elitan** [comment]
Yes. That's correct.
