### ISSUE TITLE
Generic OAuth Provider 

### ISSUE THREAD

**Issue by danvim** [nhost/hasura-backend-plus#389]
I've stumbled upon this repo while researching for Hasura and JWT authentication server boilerplate. I see that the docs hasn't been completed yet, and so I wanted to ask here if it's possible/easy to add a custom third party OAuth service, possibly from a privately maintained GitLab server or from other lesser known providers.

Otherwise, how complex would it be to add one in a repo fork if I may ask? (I haven't read deep in the source code)

**Comment by elitan** [comment]
We use Passport.js so I think it's pretty easy.

**Comment by danvim** [comment]
@elitan Could this be a potential feature? Generic OAuth seems to be quite a universal feature, as supported by e.g.: [Grafana](https://grafana.com/docs/grafana/latest/auth/generic-oauth/), [Wiki JS](https://github.com/Requarks/wiki) (which might not be as well-known, but I just personally really like).

I see there's a passport module for generic oauth as well. I sense this may potentially be linked to this as well:

https://github.com/nhost/hasura-backend-plus/blob/255811132f146d926afc7112efaeac80bbae36a0/src/routes/auth/providers/utils.ts#L49
