### ISSUE TITLE
[question] how to implement "remember me"

### ISSUE THREAD

**Issue by beebase** [nhost/hasura-backend-plus#393]
I was wondering how to avoid forcing a user to  sign in each time they open a (mobile) app.
As I understand, JWT's by default, expire and refresh every 15 minutes.

**Comment by beebase** [comment]
Looks like JWT's are refreshed automatically even if you close an app and open again next day.
I suppose you should explicitly use auth.logout() to end a user's logged in state.

**Comment by elitan** [comment]
Correct.

The JWT token expires after 15 minutes but gets automatically refreshed using a refresh token. The refresh token is saved in the browser/mobile and is valid for one year (configurable).

`auth.logout()` will, as you say, log out the user (delete the refresh_token and JWT token).
