### ISSUE TITLE
REGISTRATION_CUSTOM_FIELDS syntax?

### ISSUE THREAD

**Issue by beebase** [nhost/hasura-backend-plus#397]
I'm trying to set up custom registration fields but I'm getting 400 from server.
Is there anything wrong in this code?

client call
```
auth.register(email, password, {
        name_first: "abc",
        name_last: "ggg"
      })
```
server config
```
REGISTRATION_CUSTOM_FIELDS: "name_first", "name_last"
```

**Comment by elitan** [comment]
Client call looks good.

Change env var to:

`REGISTRATION_CUSTOM_FIELDS: name_first,name_last`

**Comment by beebase** [comment]
@elitan Thanks for your snippet.
I eventually got it working like this.
(I left out the userData property(obj) and passed a nameless object as 3rd argument.)

client code
```
        auth.register(sEmail, sPassword, {
        sNameFirst: "abc",
        sNameLast: "def"
      })
```

env var
`  REGISTRATION_CUSTOM_FIELDS: "sNameFirst, sNameLast"`

**Comment by beebase** [comment]
After upgrading to latest nhost client(3.1.0) and server (2.2.4) the custom user fields remain null after registration.

client code
```
const obj = {
        email: sEmail,
        password: sPassword,
        userData: {
          sNameFirst: sNameFirst,
          sNameLast: sNameLast,
          dDateBirth: sDateBirth,
        },
      }
const {session, user} = await auth.register(obj)
```
server setting
`REGISTRATION_CUSTOM_FIELDS: "sNameFirst, sNameLast, dDateBirth"`

Registration is success (receiving back session and user) but the custom fields in the user table remain NULL.
Not getting any error messages on the server log.

**Comment by elitan** [comment]
I think your registration object is a bit off. Try:

```js
const obj = {
        email: sEmail,
        password: sPassword,
        {
          userData: {
            sNameFirst: sNameFirst,
            sNameLast: sNameLast,
            dDateBirth: sDateBirth,
          },
        },
      }
const {session, user} = await auth.register(obj)
```

**Comment by beebase** [comment]
Yes, I noticed that syntax in the docs.
Thing is, my editor (vscode) doesn't accept that as valid syntax

![image](https://user-images.githubusercontent.com/446089/111473890-c85fd800-872b-11eb-8e00-5190765d17dd.png)

**Comment by elitan** [comment]
What's the error/warning you get in your editor?

**Comment by beebase** [comment]
```
[snowpack] Unexpected token (42:0)
40: email, 
41: password, 
42: { userData: { display_name: "Joe Doe", role: }}
    ^
43: });
44:
```

Getting same error in other editor as well.
![image](https://user-images.githubusercontent.com/446089/111474409-576cf000-872c-11eb-8509-f6d04f250ab0.png)

**Comment by elitan** [comment]
Oups, you're right. I should be:

```js
const obj = {
  email: sEmail,
  password: sPassword,
  options: {
    userData: {
      sNameFirst: sNameFirst,
      sNameLast: sNameLast,
      dDateBirth: sDateBirth,
    }
  }
}
```

**Comment by beebase** [comment]
cool, working.
thanks.
