### ISSUE TITLE
getting 404 when uploading file

### ISSUE THREAD

**Issue by beebase** [nhost/hasura-backend-plus#398]
I'm getting a 404 from server when trying to upload an image from a file input in the browser

client code
```
storage.put(`/public/${readResult.fileName}`, readResult.base64)
```

resulting POST url
```
https://....com/storage/o/public/logo.png
```

server log
```
OPTIONS /storage/o/public/logo.png 204 0 - 0.556 ms
Error: Not Found
    at exports.uploadFile (/app/dist/routes/storage/upload.js:17:30)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  data: null,
  isBoom: true,
  isServer: false,
  output: {
    statusCode: 404,
    payload: { statusCode: 404, error: 'Not Found', message: 'Not Found' },
    headers: {}
  }
}
POST /storage/o/public/logo.png 404 60 - 66.389 ms
```

**Comment by elitan** [comment]
If you're uploading base64 try:

```
await storage.putString(`/public/${readResult.fileName}`, readResult.base64, 'base64');
```

`storage.put()` is better if you're just getting a file from a `<input type="file"...` element. Check here:

https://github.com/nhost/nhost-react-typescript-example-app/blob/master/src/components/app/files.tsx#L133-L139

**Comment by bravcmo** [comment]
I'm getting this same error when using `storage.put` - the network request from the react native app shows the header token and I'm trying to write to `public/somePath` which should be writable ... is there another security step for the storage API?

**Comment by elitan** [comment]
> I'm getting this same error when using `storage.put` - the network request from the react native app shows the header token and I'm trying to write to `public/somePath` which should be writable ... is there another security step for the storage API?

Could you provide the network request, the code you have to make that request, and your storage rules?

**Comment by bravcmo** [comment]
The code is 

```    const uploadImageAsync = async (pickerResult) => {
        try {
            console.log(avatar)
            const profileFile = await fetch(avatar.uri);
            const blob = await profileFile.blob();

            await storage.put(`/public/avatarFileName`, blob)
                .then(result => console.log(result))
                .catch(err => console.log(err))
        }
        catch (e) {
            console.log('Something errored ' + e)

        }
    }
```
Having trouble copying the iOS Simulator network logs, but it's returning as a 404 Not Found 

Where does one set the storage rules?  Is there a setting in the Nhost minio console or is there a yaml file I'm missing - if so where does it go?  Many thanks - really love the market fit of your service.

**Comment by elitan** [comment]
@bravcmo If you're using [Nhost](https://nhost.io) you can see the Storage rules under: Settings -> Storage rules.

The default storage rules allow logged-in users to upload files, and anyone to download files in the `public/*` directory.

Is the user logged in when uploading this file?

You can also try to change the storage rules to something like:

```
[...]
  /public*:
    write: 'true'
    read: 'true'
```

**Comment by bfritscher** [comment]
Documentation is a bit light, but looking at the source code and the unit test, to upload a file you must make a POST request of type multipart/form-data and the variable of the file must be named "file"

**Comment by bravcmo** [comment]
I tried `/public*` and `/public/*` to know avail - still getting 404 with these:
```

functions:
  isAuthenticated: 'return !!request.auth'
  isOwner: "return !!request.auth && userId === request.auth['user-id']"
  validToken: 'return request.query.token === resource.Metadata.token'
paths:
  /public*:
    write: 'true'
    read: 'true'
  /user/:userId*:
    write: 'isOwner(userId)'
    read: 'validToken()'
```

**Comment by bravcmo** [comment]
I've tried `storage.put` and `storage.putString` but neither have worked.  `put` will successfully push the fileName to the server, but with zero bytes.  My last resort will be to just use Axios to call the REST api directly, but it appears that the `storage` is doing that itself within the API.  Perhaps this is an issue unique to React Native, but I imagine it will be a common use.  I will update this and my starter repo upon finding a solution.

**Comment by beebase** [comment]
@bravcmo  Are you by any chance getting this error in your client log?
Not sure if this applies to react-native cause it's probably browser related
I've had this error with a ProgWebApp.

`net::err_upload_file_changed`


This happens consistently when I try to upload a file from google drive using an android phone.
(known bug in chrome, not fixed yet)
https://stackoverflow.com/questions/63063277/upload-file-cause-the-error-neterr-upload-file-changed
Some people also have this problem with other cloud drives
But again, maybe not related to react-native.


If you're not getting that error, maybe you can test with following code that works in my app.
Sending the file as base64 to the server didn't work for me.
I ended up just sending the entire file object from the input file select.
You should be able to write to "/public/.." without having to change any permissions.


HTML input file select
```
 <input
    accept="image/*,video/*"
    on:click={onClick}  // Svelte syntax, replace with regular JS 
    on:change={onFileChange} // Svelte syntax,  replace with regular Js
    name="file"
    type="file"
  />
```

onChange method
```
   import {storage} from ".../nhost.js"
   ...
  const onFileChange = (e) => {
    const File = e.target.files[0]
    if (!File) {
      console.log(f, "no File selected")
    } else {
      try {
        const path = "/public/test.png"
        storage.put(path, File, null, (progress) =>
          console.log("progress", progress.loaded)
        )
      } catch (e) {
        console.log("error message!!", e.message)
      }
    }
  }
```

onClick method
(clear the input value, before selecting a file)
Maybe not necessary, but some people experience problems with file uploading if value is not null to begin with.
```
  const onClick = (e) => {
    e.target.value = ""
  }
```

nhost.js (config)
```
import nhost from "nhost-js-sdk"
const config = {
  base_url: "https://myserver.com"
}

nhost.initializeApp(config)

const auth = nhost.auth()
const storage = nhost.storage()

export { auth, storage }
```

**Comment by bravcmo** [comment]
I made this entirely more complicated than it needed to be ...

If, like many RN projects, you're using React-Native-Image-Picker, the response object has everything you need.  You don't need to read the file into a File object or Blob.  Simply pass those 3 parameters in an object as the second argument to storage and the rest is handled.  I went down the RNFB rabbithole thinking there was some arcane reason why this couldn't be done, but this far more simple and universal.

```
    const handlePicker =  () => {
        launchImageLibrary({ mediaType: 'photo'}, (response) => {
            console.log('Response = ', response);
            if (response.didCancel) {
                console.log('User cancelled image picker');
            } else if (response.error) {
                console.log('ImagePicker Error: ', response.error);
            } else if (response.customButton) {
                console.log('User tapped custom button: ', response.customButton);
            } else {
                const uri = response.uri;
                const type = response.type;
                const name = response.fileName;
                const source = {
                    uri,
                    type,
                    name,
                }
                setAvatar({uri: uri})
                storage.put(name, source)

            }
        });
    };
```

**Comment by aatauil** [comment]
By the way, had the same issue. Solved it by changing `/public` in my yaml file to `/public/:fileId`. 
```yaml
 functions:
  isAuthenticated: 'return !!request.auth'
  isOwner: "return !!request.auth && userId === request.auth['user-id']"
  validToken: 'return request.query.token === resource.Metadata.token'
paths:
  /user/:userId/:
    list: 'isOwner(userId)'
  /user/:userId/:fileId:
    read: 'isOwner(userId) || validToken()'
    write: 'isOwner(userId)'
  /public/:
    list: 'true'
  /public/:fileId:
    read: 'true'
    write: 'true'
```

**Comment by elitan** [comment]
@aatauil Nice. This will allow users to upload/download files to ex `/public/image.jpg` but not `/public/user-1/avatar.jpg`.

To allow all subsequent paths you can do:

```yaml
paths:
  /public*:
    read: 'true'
    write: 'true'
 ```
 
 @beebase What's the latest on this issue?

**Comment by beebase** [comment]
@elitan If you mean the chrome issue, it still corrupts files when trying to upload directly  from google drive (using android phone). Will just have to wait for Google to fix. Other than that, file uploads are working fine with nhost. 👍
