### ISSUE TITLE
Shouldn't accounts creative through providers follow the AUTO_ACTIVATE_NEW_USERS config?

### ISSUE THREAD

**Issue by yannickglt** [nhost/hasura-backend-plus#399]
When logging with an external auth provider like Google, a new account is automatically created. However, this account is set as `active` by default even if the environment variable `AUTO_ACTIVATE_NEW_USERS` is set to `false`.

https://github.com/nhost/hasura-backend-plus/blob/f81bf6a50dbc2514f787170bc788e97949ce9607/src/routes/auth/providers/utils.ts#L97

**Comment by elitan** [comment]
The reason is that the email is already verified from the provider.

Happy to keep the discussion about this.

**Comment by yannickglt** [comment]
OK I get your point. 
At first sight, I thought this boolean was used to preserve users who signed up to be active by default. 
But I see the main goal of this field is for email verification purpose.
I close the issue 👍
