### ISSUE TITLE
Issue with Flutter and OAuth 

### ISSUE THREAD

**Issue by Fintasys** [nhost/hasura-backend-plus#400]
I've been trying since days to get Google OAuth SignIn working with Flutters oauth2_client package. 
Meanwhile I think it is an issue on hasura backend. I've tried all possible combinations but none does succeed 100%.

Settings
```
customUriScheme: 'com.example.test'
redirectUri: 'https://backend-xxxx.nhost.app/auth/providers/google/callback'
final redirectUri: 'com.example.test://'
```

**Method 1: `grantType: AUTHORIZATION_CODE`**
```
clientId: 'xxxx.apps.googleusercontent.com',
clientSecret: 'xxxx',
scopes: [
    'https://www.googleapis.com/auth/userinfo.email',
    'https://www.googleapis.com/auth/userinfo.profile'
],
enableState: true,
enablePKCE: true,
```
**Result** StatusCode 400 - Bad response (no further clue why)

**Method 2: `grantType: AUTHORIZATION_CODE`**
```
clientId: 'xxxx.apps.googleusercontent.com',
clientSecret: 'xxxx',
scopes: [
    'https://www.googleapis.com/auth/userinfo.email',
    'https://www.googleapis.com/auth/userinfo.profile'
],
enableState: true,
enablePKCE: false,
```
**Result** Almost succeeds by redirecting final callback with `refreshToken` (no accessToken) (`com.example.test://?refreshToken=xxxx`) but library throws error that `code` & `state` query parameter was not found. (Problem in Hasura or Flutter Library?) I guess that Hasura has those parameter when redirected to hasura-callback but doesn't attach them to the final callback which triggers business logic in the client that expect those parameters.

**Method 3: `grantType: IMPLICIT_GRANT`**
```
clientId: 'xxxx.apps.googleusercontent.com',
scopes: [
    'https://www.googleapis.com/auth/userinfo.email',
    'https://www.googleapis.com/auth/userinfo.profile'
],
enableState: true,
```
**Result** Succeeds but only returns `accessToken` and no `refreshToken`

I'm out of ideas and would be really grateful for some help or ideas where the mistake is hiding.

**Comment by elitan** [comment]
**Method 2**

> but library throws error that code & state query parameter was not found. (Problem in Hasura or Flutter Library?) I guess that Hasura has those parameter when redirected to hasura-callback but doesn't attach them to the final callback which triggers business logic in the client that expect those parameters.

Problem with HBP I think. We don't send code/state yet which we should do. I added an issue for it here: https://github.com/nhost/hasura-backend-plus/issues/404 Maybe that would fix your whole problem.

**Method 3**

How is the access token returned here? I thought you would only get the refresh token via a query parameter on a successful auth and redirect back to your app. (https://github.com/nhost/hasura-backend-plus/blob/master/src/routes/auth/providers/utils.ts#L136)

**Comment by elitan** [comment]
We have a Flutter/Dart SDK in the workings. OAuth is the last big thing we need to implement. I'll try to remember to update here once it's completed.

**Comment by komninoschat** [comment]
This is being solved over at https://github.com/nhost/nhost-dart.
