### ISSUE TITLE
LOST_PASSWORD_ENABLE Docker Env Fails

### ISSUE THREAD

**Issue by joshmedeski** [nhost/hasura-backend-plus#402]
Here is my docker-compse file:

```diff
version: '3.6'
services:
  postgres:
    ...
  graphql-engine:
    ...
  hasura-backend-plus:
    image: nhost/hasura-backend-plus:latest
    ports:
      - '3000:3000'
    environment:
      SERVER_URL: http://localhost:3000
      HASURA_ENDPOINT: http://graphql-engine:8080/v1/graphql
      HASURA_GRAPHQL_ADMIN_SECRET: '$HASURA_GRAPHQL_ADMIN_SECRET'
      JWT_ALGORITHM: RS256
      S3_ENDPOINT: http://minio:9000
      S3_BUCKET: hasura-backend-plus
      S3_ACCESS_KEY_ID: minio_access_key
      S3_SECRET_ACCESS_KEY: '${S3_SECRET_ACCESS_KEY:?S3_SECRET_ACCESS_KEY}'
      AUTO_MIGRATE: 'true'
+     LOST_PASSWORD_ENABLE: 'true'
volumes:
  db_data:
```

I added `LOST_PASSWORD_ENABLE` to the environmental variables, restarted the Docker container, but it has no effect.

When I run `POST /auth/change-password/request` it returns the following error:

```json
{
    "statusCode": 500,
    "error": "Internal Server Error",
    "message": "An internal server error occurred"
}
```

I'm not sure if it's because docker-compose files require true to be wrapped as a string. I looked at the source code and it looks like it should work but the 500 status code tells me the environmental variable is being ignored.

Can you please help?

**Comment by elitan** [comment]
Can you check the logs?

Either add `container_name: hbp` and do `docker logs -f hbp` to check the logs.

Or get the id of the container (`docker ps`) and do `docker logs -f <id>`.

Also, do you send an `email` with the request? Like this: https://github.com/nhost/nhost-js-sdk/blob/master/src/Auth.ts#L479-L483

**Comment by joshmedeski** [comment]
Great tip @elitan, I haven't properly configured the SMTP settings locally:

```
 Error: SMTP settings unavailable
```

I'll get that working and get back to you.

**Comment by joshmedeski** [comment]
Things are working with the proper SMTP settings configured.
