### ISSUE TITLE
OAuth management

### ISSUE THREAD

**Issue by Yagger** [nhost/hasura-backend-plus#405]
1. Store provider's access and refresh tokens in database
2. Configure provider scopes via env vars
3. ~~Allow multiple provider accounts be connected to the same user~~
Connect services (via OAuth) to already logged in user, emails don't have to match
4. Manage token rotation

**Comment by Yagger** [comment]
Came across one more feature that would be useful to add - Connecting multiple provider accounts to the same user.

Let's say I have an app that integrated Google Calendar and Facebook. I need API tokens from both providers. Currently I can login with any of them and I will have access to that one provider (storing provider's token is not implemented yet but in PR). 

Then to connect to the other provider I cannot just 

I need to set up custom workflow, and a separate tiny API server to handle this second OAuth.

**Comment by elitan** [comment]
1,2 are pretty easy. Combinaton of https://github.com/nhost/hasura-backend-plus/pull/367 and https://github.com/nhost/hasura-backend-plus/pull/433
3 is already implemented based on email. If you register with Twitter using `abc@example.com` and then register using Google using `abc@example.com` (same as with Twitter) those two accounts will be merged.
4 I don't know but is crucial to get right.

So let's expand on 4. "Manage token rotation". How does this work with different services? And how should we implement it?

**Comment by Yagger** [comment]
Edited point 3. In my fork I do [this](https://github.com/Yagger/hasura-backend-plus/commit/6fb5a2c70aeff3c94cce6a5193684b0dbae4eec3#diff-2f050f7023d9dd28a282d8d9ca1920494aa959162d3b64b4083c3d25b31dae29R54), but I'd rather split the notion of OAuth for logging in and OAuth for connecting services.

I now make //hasura-backend-plus/auth/providers/{provider} endpoint do more than it is designed for.
Better to have separate endpoint like //hasura-backend-plus/auth/providers/{provider}/connect for this specific intent.

**Comment by elitan** [comment]
Ok, yes we could do something like that. for P3.

How about P4? I think we need to do some research there?

**Comment by Yagger** [comment]
Re P4, there is no strict rules about the refresh token in OAuth 2.0 specs. It is [optional](https://tools.ietf.org/html/rfc6749#section-1.5), as well as the life time of the access token, expires_in field is [recommended](https://tools.ietf.org/html/rfc6749#section-4.2.2), but not mandatory. That leaves us with no one good way of handling it.

A bold solution could be on every /auth/token/refresh request to also refresh all the tokens from account_providers relationship. In that case we don't even have to store the access token, only the refresh token, since access token will be generated on every /auth/token/refresh request and passed to a caller.

Token refresh has to be done on the backend, since the request includes client secret. Just to make clear frontend handling is not an option.

Regarding HOW to refresh. PassportJS [cannot](https://github.com/jaredhanson/passport/issues/285) do that. There is a passportjs [plugin](https://github.com/fiznool/passport-oauth2-refresh), but it is not maintained anymore. Maybe we'll need to write a counterpart refresh token strategy for each provider.

What to do if provider token expires midst of the frontend activities? Issue a /auth/token/refresh request. Or, research which of your providers has the least access token life time and set JWT_EXPIRES_IN a bit less than that, this will ensure all the tokens are fresh all the time (given that the frontend is set to auto-refresh JWT in JWT_EXPIRES_IN interval).

**Comment by elitan** [comment]
Could we handle the refresh tokens using Hasura's [cron-triggers](https://hasura.io/docs/latest/graphql/core/scheduled-triggers/create-cron-trigger.html)?

The cron-trigger would trigger an endpoint in HBP that would be responsible to update the refresh token for every provider that is configured and active.

In that specific HBP endpoint, we could write specific code per provider to update the refresh token (if needed).

**Comment by Yagger** [comment]
Not sure about cron triggers, that may bring scalability issues, since all providers will refresh all the time no matter if they are used or not. Upon request seems better option. Or event triggers? that will only refresh when there is some activity on the user record (last_login field or smth). Not so sure.

**Comment by elitan** [comment]
Make sense.

I think we should do some research into what providers have what requirements for refreshing tokens. So we know what we're dealing with.

Then try to find a solution based on that.

The research result could look something like this:

Provider 1: Token valid for 1 hour.
Provider 2: Token never expires
Provider 3: Token valid for 30 days

We could possibly provide endpoints to each provider to refresh all tokens. Or specify a userID to refresh a token for only that user. Then let the developer implement when and how to trigger that endpoint.

---

Google's tokens seem to be valid for 1 hour ([link](https://stackoverflow.com/a/45904670/885968)). To have tokens updated prematurely does sounds wasteful.

**Comment by Yagger** [comment]
Or better yet, provide //hasura-backend-plus/auth/providers/{provider}/refresh endpoint and let the developer handle it in similar manner as [JWT refresh](https://nhost.github.io/hasura-backend-plus/guide.html#jwt).

**Comment by Yagger** [comment]
@elitan I've implemented most of it. But I added many lines to providers/utils.ts.

**Comment by komninoschat** [comment]
Split into #476, #477, #478.
