### ISSUE TITLE
Crop and toFormat

### ISSUE THREAD

**Issue by elitan** [nhost/hasura-backend-plus#412]
As requested by @masonhipp for image transformation:

`crop`
https://sharp.pixelplumbing.com/api-resize#resize

`toFormat`
https://sharp.pixelplumbing.com/api-output#toformat

**Comment by komninoschat** [comment]
Will be closed by #463.

**Comment by elitan** [comment]
We’ve decided to only fix bugs and refactors on Hasura Backend Plus from now on because we’re working on a new auth + storage service for Hasura. Currently, these new repositories are private but will be open-sourced soon. 

We’ll have your issue in mind when developing the new services. So thanks for filing this issue

 This means I’ll close this issue for now.
