### ISSUE TITLE
Cookie is not allowed 

### ISSUE THREAD

**Issue by joshhopkins** [nhost/hasura-backend-plus#414]
Would appreciate any insight into this: https://github.com/nhost/nhost-js-sdk/issues/49

**Comment by joshhopkins** [comment]
I had a quick look [here](https://github.com/nhost/hasura-backend-plus/blob/0c030d7bc1672f02e5fcf04d11687cff3e92c23d/src/shared/validation.ts#L112) at it appears that there something odd going on with validation. See output:

```
[Error [ValidationError]: "cookie" is not allowed] {
  _original: { cookie: true },
  details: [
    {
      message: '"cookie" is not allowed',
      path: [Array],
      type: 'object.unknown',
      context: [Object]
    }
  ]
}
```

**Comment by elitan** [comment]
Can you double-check your version by visiting the `/version` URL?

**Comment by joshhopkins** [comment]
{"version":"v2.2.4"}

**Comment by elitan** [comment]
Strange, the code you link to do allow for the `cookie` property. Anything else in the hbp logs?

**Comment by joshhopkins** [comment]
Ok, still testing, but I think I've finally traced it down. At some point I set `ANONYMOUS_USERS_ENABLE=TRUE`, which the `nhost-js-sdk` client doesn't handle yet. Understand this feature is experimental, so it's my fault. At some point I'd imagine the `cookie` property will be ignored in the case that `useCookies: false`.

**Comment by Uthpala** [comment]
Okay I ran in to the same issue. I am too using nhost-js-sdk v3.

Update Hasura Backend Plus to 2.2.4 works - https://github.com/nhost/hasura-backend-plus/releases/tag/v2.2.4

In your local machine you can update HBP to 2.2.4 by updating the config.yaml inside the nhost directory and re-running nhost dev.

**Comment by elitan** [comment]
Upgrading seems to solve this issue.
