### ISSUE TITLE
Store user data from GitHub

### ISSUE THREAD

**Issue by imzedi** [nhost/hasura-backend-plus#415]
I have implemented GitHub social login. works perfectly.
Currently, we are able to store basic user info required for authentication but
Is there any way to also store some optional user's data directly from Github while Registering from HBP.
i.e. some optional data like twitter_username, location, login(Github username), etc. Populate these data directly to DB?

**Comment by elitan** [comment]
Yep, let's unify this conversation here: https://github.com/nhost/hasura-backend-plus/issues/415
