### ISSUE TITLE
Disable public registration

### ISSUE THREAD

**Issue by elitan** [nhost/hasura-backend-plus#416]
Should still be open with `x-admin-secret` so only admins can create users.

**Comment by plmercereau** [comment]
I would use the same env var to enable public registration, but to disregard it when x-admin-secret is in the headers

**Comment by elitan** [comment]
> I would use the same env var to enable public registration, but to disregard it when x-admin-secret is in the headers

Yea, agree.

Any suggestion for naming the env var? 

```
REGISTRATION_ENABLE
AUTH_REGISTRATION_ENABLE
```

**Comment by AntonBozhinov** [comment]
I think it should be ALLOW_USER_SELF_REGISTRATION? Or something around self registration. A more general name might be a bit misleading?

**Comment by komninoschat** [comment]
I propose `ADMIN_ONLY_REGISTRATION` as the env variable.

**Comment by nikolowry** [comment]
Somewhat off-topic, but is it possible to to allow public registration (with just email) that depends on an admin's approval? It's more so "applying to be a user" rather than "registering to be a user". Building a niche-professional community where each user's qualifications must be vetted and approved manually prior to allowing access.

**Comment by nikolowry** [comment]
Would also be great to have a feature that allows public registration, but requires admin approval for user activation (i.e "request to join"). Passwords wouldn't be required when "requesting to join", and the approval/activation email would include a ticket for setting the new users' password. 

Sidebar: Currently tasked to implement such a feature as I described above. Any advice on how to model this abstraction with the current code base would be greatly appreciated.

**Comment by komninoschat** [comment]
@elitan What are your thoughts regarding the above? It's the invite-only registration feature. I think that if we choose to implement this, though, it will have to be a new PR.

**Comment by elitan** [comment]
@nikolowry @komninoschat I created a separate issue for that feature. It's a bit different from an "invite-only" feature because the users should request to join themselves. Let's continue that conversation on the newly created issue:

https://github.com/nhost/hasura-backend-plus/issues/558
