### ISSUE TITLE
Deploying HBP via docker-compose

### ISSUE THREAD

**Issue by RubenVanEldik** [nhost/hasura-backend-plus#419]
Hi Johan and others!

I found HBP a while ago and last week I finally had some time to start experimenting with it. The experience so far is great! I have created a small app that works locally and I am now trying to deploy the docker-compose file to a DO droplet. The 'problem' I have now is that the `hasura-backend-plus` server is only accessible via port 3000 (while the Hasura server is accessible without specifying a port). Is there a way to make both the Hasura server and HBP accessible without specifying a port in the URL? Or is it not recommended at all to deploy the Hasura and HBP server via docker-compose in the same droplet?

My apologies if this is a very dumb question. :p I am a front-end developer, so I don't have a lot of experience with servers. 

Ps. I would love to contribute to this awesome project and I see that there are still some gaps in the documentation. Would you appreciate PR to improve the documentation?

**Comment by RubenVanEldik** [comment]
Update. I am following the [deployment guide from Hasura](https://hasura.io/docs/1.0/graphql/core/deployment/deployment-guides/digital-ocean-one-click.html#step-4-edit-the-caddyfile-and-change-80-to-your-domain) and trying to implement the Caddy service.

I got it working using two separate subdomains:

```
api.mysite.com {
  reverse_proxy graphql-engine:8080
}

hbp.mysite.com {
  reverse_proxy hasura-backend-plus:3000
}
```

I would love to use the same subdomain (api). If anyone knows if such a thing is possible, I would love to hear it :)

```
api.mysite.com {
  reverse_proxy graphql-engine:8080
  reverse_proxy hasura-backend-plus:3000
}
```

**Comment by Svarto** [comment]
@RubenVanEldik glad to see you got it to work. It wont be possible from your end to have all endpoints under one subdomain, if you don't write a rather advanced router to route the correct requests to the right internal endpoint.

I would also mention that it might not be very preferable, it makes it easier on many dimensions to keep them separated (remember that the graphql-engine is a configured Hasura setup which is under active development).

**Comment by RubenVanEldik** [comment]
Thank you @Svarto for your response!

I indeed run the dev server now under api.mydomain and hbp.domain. This works great!

Regarding 'keeping them separated', do you mean to keep just the subdomains separated or would you also recommend to have two separate droplets, one for Hasura and one for HBP?
