### ISSUE TITLE
Username based login support

### ISSUE THREAD

**Issue by imzedi** [nhost/hasura-backend-plus#424]
Is there any implementation of username based login system in current version?

If it is there then please tell me how to enable it.

**Comment by elitan** [comment]
No there is not. Do you want username + email or only username without email?

If you want a username without email you can append `@example.com` to users' username when they register and log in. Something like: `<username>@example.com`.

This is the same suggestion that [Firebase gives](https://stackoverflow.com/a/37490634/885968).

**Comment by imzedi** [comment]
@elitan  Thanks for responding.
yes, I want both username and email. I wish we will have this feature support for HBP in the near future 🙌.

**Comment by elitan** [comment]
We will probably not implement it in the near future. Does my (and Firebase's) answer above work for you?

**Comment by imzedi** [comment]
Not for my current project but surely it will be very helpful for my next project. Thanks 👍

**Comment by elitan** [comment]
Cool. I'll close this issue for now. Good luck with your project(s) :)
