### ISSUE TITLE
Documentation: missing information on Storage image transformation feature

### ISSUE THREAD

**Issue by bfritscher** [nhost/hasura-backend-plus#429]

**Comment by RubenVanEldik** [comment]
Hi @bfritscher,

Could you elaborate what you mean? As far as I know there are now image transformation capabilities in HBP.

**Comment by RubenVanEldik** [comment]
You’re completely right! I had no idea this was a part of HBP! I was literally yesterday looking at image CDN’s like Cloudinary just to resize my images on the fly, but apparently it’s already built in! 

I’m gonna try this feature out this weekend, if I have time I’ll make a PR for the documentation.

**Comment by elitan** [comment]
Perfect @RubenVanEldik. Thanks.

**Comment by RubenVanEldik** [comment]
@bfritscher I added the documentation today, see https://github.com/nhost/hasura-backend-plus/pull/447.

I love it that it's possible to transform the images on the fly, so I also added some new transformations (format, position, rounding, and blur), but they're obviously not yet merged. So they're not available yet. :)

**Comment by bfritscher** [comment]
@RubenVanEldik nice work on your commits!
As you have done some tests with the code I have two questions:

1) Did you by chance have the Etag bug? https://github.com/nhost/hasura-backend-plus/issues/430
2) I have seen that we always do transformer.rotate() this rotates the image based on its exif metadata (https://sharp.pixelplumbing.com/api-operation#rotate) . @elitan  What was the reason for adding this as default? Maybe we need to document this behavior?

**Comment by RubenVanEldik** [comment]
1. I just looked into the ETag but and commented in that issue.
2. You're completely right that the rotate transformation is a bit unintuitive, but as far as I can tell its indeed to rotate the image to match the EXIF data. I created a quick PR with a comment to explain it for new users (https://github.com/nhost/hasura-backend-plus/pull/450)

**Comment by elitan** [comment]
#447 merged.
