### ISSUE TITLE
Storage ETag on GET has escaped quotation marks

### ISSUE THREAD

**Issue by bfritscher** [nhost/hasura-backend-plus#430]
```
{
"key":"public/test.jpg","AcceptRanges":"bytes","LastModified":"2021-03-08T16:46:38.000Z","ContentLength":80639,

"ETag":"\"63104255d2f366a1e2880a668f43b0e9\"",

"ContentType":"image/jpeg","Metadata":{"token":"12316634-15ac-4f8e-8770-a07f91f1ed6c"}}
```

**Comment by RubenVanEldik** [comment]
I am able to reproduce this. When requesting an untransformed image the ETag string will have double quotes in the string. However, a transformed image (eg. `...?w=300`) does not have these extra double quotes.

When I started looking further into it, it started to look like the double quotes is actually how the standard is specified! 🙃 (see [Mozilla](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag#directives) and [W3](https://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html#sec3.11)) Therefore I think that the implementation for the transformed images is wrong, while the standard implementation is correct.

**Comment by RubenVanEldik** [comment]
I created a PR to add double quotes to the ETag of transformed images as well

**Comment by RubenVanEldik** [comment]
I think this is the correct implementation, please let me know if I misread the specification of the protocol! :)

**Comment by bfritscher** [comment]
Yes, you are right.

**Comment by elitan** [comment]
#449 merged.
