### ISSUE TITLE
refresh token in the payload

### ISSUE THREAD

**Issue by Vincebe** [nhost/hasura-backend-plus#431]
Hello,

When logging in, is there a way to get the refresh token in the payload instead of cookie-set?

I'm trying to get hbp working with nuxt-auth ([https://auth.nuxtjs.org/schemes/refresh](https://auth.nuxtjs.org/schemes/refresh) 

Thanks

**Comment by elitan** [comment]
Yes, send `cookie: false` when you log in.

**Comment by Vincebe** [comment]
Thanks!
