### ISSUE TITLE
Username and password do not match

### ISSUE THREAD

**Issue by Vincebe** [nhost/hasura-backend-plus#432]
Hello,

I'm testing HBP with nuxtjs. 

After a successfull register, everything is fine in db, but i cannot login (username and password do not match).

After a quick check in the login controller, bcrypt passwords compare returns false at this line:
`await bcryptjs_1.default.compare(password, password_hash)`

I double checked query / request / headers / body, everything is fine (and the password is obviously correct).

Thanks

**Comment by elitan** [comment]
Do you use `nhost-js-sdk`?  What version?

Can you provide some code with the registration and login that you do? Maybe also with screenshots from the network request log in your browser?

**Comment by Vincebe** [comment]
No, simple axios post at this time (validating Hasura + HBP for a project).
It's been 2 hours, I checked everything twice. And of course, right after posting, I just found a stupid error in my code.
Sorry...

**Comment by elitan** [comment]
hehe, no worries. It happens to the best of us. Good luck with your project!
