### ISSUE TITLE
Consider providing additional OTP configuration details from the /mfa/generate endpoint

### ISSUE THREAD

**Issue by shyndman** [nhost/hasura-backend-plus#435]
I would like to be able to generate a TOTP from the return of `/mfa/generate`...but found that `otp_secret` doesn't provide enough information to configure the code generation algorithm (unless you assume a few things).

Decoding the QR code reveals that there is in fact additional configuration available:

```
otpauth://totp/HBP:{guid}?secret=XXXXXXXXXXXXXXXX&period=30&digits=6&algorithm=SHA1&issuer=HBP
```

And this is exactly what I was missing to feed the algo!

I realize that the `period`, `digits`, and `algorithm` values are the `otplib` defaults, but until I'd decoded that QR and read over the `otplib` docs, I had no idea. And until I had, `otp_secret` wasn't useful (so this is a bit of a usability/DX issue).

Just a thought!

**Comment by shyndman** [comment]
The more I look at this though, the more I see most libraries have these defaults...so maybe not so much of an issue.

**Comment by elitan** [comment]
Yea let's keep these default values for now. The `issuer` value can be set with the env var: `OTP_ISSUER`
