### ISSUE TITLE
Increase TOTP window

### ISSUE THREAD

**Issue by RubenVanEldik** [nhost/hasura-backend-plus#437]
When a user enters their TOTP code, it gets checked against the current timestamp, but when a user is 1 second late the request fails and they have to re-enter a completely new TOTP code. This is not a great UX, I think it would be better to also accept the TOTP of the previous 30 seconds since it takes some time to enter the TOTP code in the first place (especially on mobile). I took a look under the hood and it looks like the otplib has already this option (https://github.com/yeojz/otplib#totp-options).

**Comment by RubenVanEldik** [comment]
Since HBP is now also working in dev mode for me, I was able to create the PR myself, see: https://github.com/nhost/hasura-backend-plus/pull/452.

**Comment by elitan** [comment]
https://github.com/nhost/hasura-backend-plus/pull/452 merged
