### ISSUE TITLE
Which values are accepted by LOG_LEVEL?

### ISSUE THREAD

**Issue by diogoeichert** [nhost/hasura-backend-plus#440]
The accepted values for `LOG_LEVEL` can't be found in the documentation:
https://nhost.github.io/hasura-backend-plus/configuration.html#environment-variables

It would be also helpful to highlight the default behavior when this environment variable is not set.

**Comment by elitan** [comment]
`LOG_LEVEL` is only piped to the Hasura CLI when applying migrations/metadata. You can see the different values here: https://hasura.io/docs/latest/graphql/core/hasura-cli/hasura.html#options

```
--envfile string      .env filename to load ENV vars from (default ".env")
-h, --help                help for hasura
    --log-level string    log level (DEBUG, INFO, WARN, ERROR, FATAL) (default "INFO")
    --no-color            do not colorize output (default: false)
    --project string      directory where commands are executed (default: current dir)
    --skip-update-check   skip automatic update check on command execution
```

**Comment by diogoeichert** [comment]
Thanks for the info. How about adding a link to https://hasura.io/docs/latest/graphql/core/hasura-cli/hasura.html#options from the LOG_LEVEL section in https://nhost.github.io/hasura-backend-plus/configuration.html#environment-variables, then?

**Comment by elitan** [comment]
I think that's a good idea. 👍  Could you do a PR on it?
