### ISSUE TITLE
Empty "Enable emails" section in docs

### ISSUE THREAD

**Issue by diogoeichert** [nhost/hasura-backend-plus#442]
While browsing the docs for the [registration process](https://nhost.github.io/hasura-backend-plus/configuration.html#registration), there's a link to [configure the connection to a SMTP server](https://nhost.github.io/hasura-backend-plus/configuration.html#enable-emails) but the section in empty. Are the docs missing or is it a broken link?

**Comment by elitan** [comment]
The docs are missing.

You can see the SMTP settings here: https://nhost.github.io/hasura-backend-plus/configuration.html#authentication-2

Every env var that starts with `SMTP_` is related to email.
