### ISSUE TITLE
One account per email address

### ISSUE THREAD

**Issue by RubenVanEldik** [nhost/hasura-backend-plus#453]
Currently its possible to create multiple account per email address via the `+` symbol (e.g. example+one@example.com and example+two@example.com). 

For most applications this is fine, but I would like to disable this to make it harder to create spam accounts. I was thinking about how to do this in HBP, and I think there are two options:

1. Don't do it in HBP, just create an extra check constraint on the email column in Postgres. This has the drawback that the users won't get a clear error.
2. Add a `ONE_ACCOUNT_PER_EMAIL` environment variable. When this variable is enabled, the `selectAccountByEmail` function will need to use a query with an _ilike filter (and the email has to be transformed to `example%@example.com`) instead of the current _eq filter.

I would love to hear what y'all think about this and what the best solution would be. If you agree with the second option, I could create a PR later this week.

**Comment by Destreyf** [comment]
@RubenVanEldik I'm just going to chime in here on my opinions.

I understand wanting to limit users to a single email address/account, however there are some problems to consider.

Your example of using a wildcard with an ilike has a massive drawback, given these two email addresses, you'd be blocking off access.

User 1: nonexistant@gmail.com
User 2: nonexistant1@gmail.com

The ilike wildcard (%) will match both email address options, preventing one or the other from signing up.

Further more based on the specification for email addresses, you can use a + character as a valid portion of the local (username) portion of the email address, below are the rules for the local portion.

#### Local-part
- uppercase and lowercase Latin letters A to Z and a to z.
- digits 0 to 9.
- printable characters !#$%&'*+-/=?^_`{|}~
- dot . , provided that it is not the first or last character and provided also that it does not appear consecutively (e.g., John..Doe@example.com is not allowed).

This creates a risk of breaking compliance with the email addresses.

Google (gmail) prevents users from using a + character in the local-part for their sign up, but it's technically a valid character for self hosted email, or possibly even other email services, the way that Google handles the + is they automatically convert the following portion into a label, which makes them technically not spec compliant.

Hopefully this makes sense, but I believe it's a bad idea to implement a non spec compliant feature/functionality.

I believe the best way to handle this case, where it's specific to your use case, is to enforce it via validation on your client side.  It does mean that if someone understands your API, they could take advantage of this as a potential vulnerability.

Another way that I could see this being implemented is break it into multiple parts and then check for multiple variants.

For example, using `user+label@domain` you could break it apart into `user`, `label`, `doman`, and then do a check for `user@domain` in the validation call back, this way the behavior can be more sanely run.  

This comes with a drawback of needing to do a query for multiple values, one for `user+label@gmail.com`, one for `user@gmail.com`, and potentially doing a wildcard search (which is where this can get messy) of `user+%@domain`, this last one creates a possible violation of the spec.

I also think there could be some sort of webhook option that does validation for hasura-backend-plus, where you could tie your own code to check the email address or other fields that happen during registration (I would enforce password exclusion with this option though). 

Maybe hasura-backend-pus could offer other ways to integrate validation options into the registration system, or maybe it already does and I've missed it, but it would be nice to be able to either override or extend existing logic within hasura-backend-plus.

Those are just my thoughts on this feature request, I think the community can definitely discuss this in more depth.

**Comment by RubenVanEldik** [comment]
Thank you for the great response @Destreyf!

I had no idea that the way Gmail (and a few others) handle the `+` symbol is not spec compliant. This makes it indeed a lot harder and probably not feasible to implement.

Your idea to add the option to manually extend the validation is interesting, but I have not enough knowledge about security to truly assess this idea. It might be handy to create a new issue for the idea, since it sounds interesting!

I'll close this issue for now.
