### ISSUE TITLE
Dynamically set env variable on tests

### ISSUE THREAD

**Issue by komninoschat** [nhost/hasura-backend-plus#464]
Currently, our tests load a `.env.test` file and the environmental variables do not change throughout our tests.

Here is an example from [auth.test.ts](/nhost/hasura-backend-plus/tree/master/src/routes/auth/auth.test.ts):

```typescript
const pwndPasswordIt = HIBP_ENABLE ? it : it.skip
pwndPasswordIt('should tell the password has been pwned', async () => {
  const {
    status,
    body: { message }
  } = await request.post('/auth/register').send({ email: 'test@example.com', password: '123456' })
  expect(status).toEqual(400)
  expect(message).toEqual('Password is too weak.')
})
```

I propose code like such to be refactored to something like:
```typescript
it('should tell the password has been pwned', async () => {
  process.env.HIBP_ENABLE = 'true'
  const {
    status,
    body: { message }
  } = await request.post('/auth/register').send({ email: 'test@example.com', password: '123456' })
  expect(status).toEqual(400)
  expect(message).toEqual('Password is too weak.')
  process.env.HIBP_ENABLE = 'false'
})
```

(We could find something prettier than directly changing `processs.env` and reverting back, but you get the idea).

This way, we will be able to test whether, for example, pwned passwords are checked if the env flag is set **and** whether they are not checked if the env flag is unset.

We would also need to refactor [registration.ts](nhost/hasura-backend-plus/tree/master/src/shared/config/authentication/registration.ts) and all the config files that deal with env variables to be able to react to runtime env variable changes.

cc: @elitan, @nunopato

**Comment by elitan** [comment]
I've been thinking about this too. If we can solve this by dynamically set env vars it would be great! Totally approve!
