### ISSUE TITLE
Use express-boom-v2

### ISSUE THREAD

**Issue by komninoschat** [nhost/hasura-backend-plus#471]
We currently use the `@hapi/boom` package directly for our HTTP errors. I propose we instead use [this](https://github.com/hasithaishere/express-boom-v2) package which wraps `@hapi/boom` as an express middleware.

Doing so will result in more testable and clearer code:
```typescript
throw Boom.badImplementation('SMTP settings unavailable') // Uses throw and weird global variable, bad practice.
```
vs.
```typescript
return res.boom.badImplementation('SMTP settings unavailable') // 🚀
```

**Comment by komninoschat** [comment]
Furthermore, Boom errors are sometimes used outside of routes, e.g. on [jwt.ts](/nhost/hasura-backend-plus/blob/master/src/shared/jwt.ts#L47):
```typescript
if (!jwtKey) {
  throw Boom.badImplementation('Empty JWT secret key.')
}
```
We should just throw regular `Error`s in cases like the above.

**Comment by elitan** [comment]
I like the syntax of returning the http error instead 👍 . Maybe @plmercereau wants to weigh in?
