### ISSUE TITLE
Create contributing file

### ISSUE THREAD

**Issue by komninoschat** [nhost/hasura-backend-plus#483]
We should create a `CONTRIBUTING.md` file which will contain information with regards to setting up a dev environment, common issues and more.

It will make it easier for people to contribute to our project as well as improve the onboarding process for NHost.

**Comment by adithyaakrishna** [comment]
Can I work on this? 👀

**Comment by elitan** [comment]
Fixed in https://github.com/nhost/hasura-backend-plus/pull/633.

Feel free to send PR for updates.
