### ISSUE TITLE
Auth: Consider adding subject and issuer claims to JWT

### ISSUE THREAD

**Issue by dthyresson** [nhost/hasura-backend-plus#495]
In RedwoodJS auth, when we decode the token on the api side, we get a value like:

```js
"decoded": {
  "https://hasura.io/jwt/claims": {
    "x-hasura-user-id": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx",
    "x-hasura-allowed-roles": [
      "user",
      "me"
    ],
    "x-hasura-default-role": "user"
  },
  "iat": 1619266575,
  "exp": 1619267475
}
```

While both claims are optional, it would be useful for us to have the subject (`sub` aka the user id), issuer (`iss` that nhost.io issued the token) as commonly presented JWT claims (https://auth0.com/docs/tokens/json-web-tokens/json-web-token-claims#reserved-claims).

> iss (issuer): Issuer of the JWT

```
4.1.1.  "iss" (Issuer) Claim
   The "iss" (issuer) claim identifies the principal that issued the
   JWT.  The processing of this claim is generally application specific.
   The "iss" value is a case-sensitive string containing a StringOrURI
   value.  Use of this claim is OPTIONAL.
```

> sub (subject): Subject of the JWT (the user)

See: https://github.com/nhost/hasura-backend-plus/blob/b788cf7f53301f6e2bad2499b4d7f3942862653a/src/shared/jwt.ts#L138

Maybe something along lines of:

```js
export const createHasuraJwt = (accountData: AccountData): string =>
  sign({
    [CONFIG_JWT.CLAIMS_NAMESPACE]: generatePermissionVariables(accountData, true),
    sub: accountData.user.id,
    iss: 'nhost'
  })
```

The other option for RedwoodJS is for us to parse the decoded JWT and then inject those claims ourselves as part of our auth's decoder -- which is fine. 

The "role" info could be done the same way.

I'll follow-up with an example of how RedwoodJS can do that and what it might look like.

**Comment by dthyresson** [comment]
Follow up as have added custom decoding in RedwoodJS and can return the decoded JWT in a format with the sub, issuer, and roles in a format that more resembles the structure needed.

```js
"decoded": {
      "https://hasura.io/jwt/claims": {
        "x-hasura-user-id": "2dd1bd63-xxxx-4ad1-xxxx-8edfd4e5935a",
        "x-hasura-allowed-roles": [
          "user",
          "me"
        ],
        "x-hasura-default-role": "user"
      },
      "iat": 1619269486,
      "exp": 1619270386,
      "sub": "2dd1bd63-xxxx-4ad1-xxxx-8edfd4e5935a",
      "iss": "nhost",
      "roles": [
        "user",
        "me"
      ]
    },
```

**Comment by dthyresson** [comment]
See: https://github.com/redwoodjs/redwood/pull/2350 for an implementation example.

**Comment by nunopato** [comment]
@dthyresson thanks for putting this up. We will work on adding those optional claims and will release it sometime this week.

**Comment by elitan** [comment]
Fixed in https://github.com/nhost/hasura-backend-plus/commit/a98c7d3c11b867702d30782a4759e0a2d2df3df3#diff-dbcec59a111c6da3f2010268b869cceab04b04525db9ad059f6c5f096913cfbdR120
