### ISSUE TITLE
NHost Dashboard Auth Analytics

### ISSUE THREAD

**Issue by fullakingi** [nhost/hasura-backend-plus#509]
Analytics: see what users are more active. Internally track how often and for how long users are logged in simply by tracking every time a user logs in and refreshes the token. 
<img width="1369" alt="Screen Shot 2021-05-06 at 5 29 57 PM" src="https://user-images.githubusercontent.com/6522361/117273264-16819400-aeb0-11eb-8633-c36d0dc5306e.png">

**Comment by elitan** [comment]
I want this too! It will generate data to do some cool data visualization too.

I suggest we track the following:

- Every login per user
- Every refresh token update by a user

This will enable us to see:

- How many users were logged in for the last x days, between date x and y in my app?
- How many minutes were spent by users in my app?
- How is my app's user retention?
- Cohort analyst.

**Comment by fullakingi** [comment]
@elitan "top pages", the thinking was to have a way to identify which features/pages/functionality of an applicatio users interact with the most. This would focus efforts on the most used features for any auth based project. I realise general page views can be gleaned via Google Analytics. Perhaps there is some way to combine user analytics with app content analytics, like a typical pivot table. If so there would need to be some way to access the user tracked data and make it available to the developer.

**Comment by elitan** [comment]
> typical pivot table
What's that?

@fullakingi Also, if you want. Please suggest a table structure where we could store all this analytics data. It could be a super quick draft but just so we can sync our thoughts a bit on what we want to build here.

**Comment by fullakingi** [comment]
@elitan [pivot table ](https://en.wikipedia.org/wiki/Pivot_table)are very helpful. Just did a quick bit of research. PostgreSQL allows the creation of pivot tables using the [tablefunc module](https://www.postgresql.org/docs/9.2/tablefunc.html).  That's about as far as I get before I get confused by the syntax.

Here is an example of method to get the desired data. This is raw example without much statistical finesse. I guess there are better methods using PostGres/GraphQL, but I am not sure as I just learning PostGres)

--table 1 example start--

EXAMPLE TABLE 1 USERS LOGIN
ID  |   UserName  |   Login  IP Address | Timestamp
01  |  Pablo | 35.61.1.99 | 10:08am  11 June 2021
02  |  Pablo | 35.61.1.99 | 21:08pm  12 June 2021
..etc..

Then lookup/query by 'ID = value' and return results.

RESULTS OF QUERY
01  |  Pablo | 35.61.1.99 | 10:08am  11 June 2021
02  |  Pablo | 35.61.1.99 | 21:08pm  12 June 2021

TOTAL LoginCount for UserName (Pablo) = 2

--table 1 example end --

--table 2 example start --

EXAMPLE TABLE 2 PAGE VISITS
ID |  NamePage  |   VisitorID   |   Timestamp
P01  |  SearchPage  |   XXID01   | 11:34pm 13 July 2021 
P02  |  ListPage  |   XXID01   | 08:09pm 13 July 2021 
P03  |  SearchPage  |   XXID01   | 09:19pm 13 July 2021 

..etc..

Then lookup/query by 'VisitorID = XXID01' and return results.

RESULTS OF QUERY
P01  |  SearchPage  |   XXID01   | 11:34pm 13 July 2021 
P02  |  ListPage  |   XXID01   | 08:09pm 13 July 2021 
P03  |  SearchPage  |   XXID01   | 09:19pm 13 July 2021 

TOTAL PageVisits = 
SearchPage = 2
ListPage = 1

--table 2 example end --

Combine the data from LoginCount and PageVisits into one table

LoginCount for UserName=Pablo = 2
PageVisits = Total = 3, SearchPage = 2 and ListPage = 1

**Comment by fullakingi** [comment]
@elitan I have found a new method for this. It looks good, check it out: https://codebycorey.com/blog/page-views-nextjs-supabase

**Comment by elitan** [comment]
Looks good! it's very write-heavy though but it's a good start. We might want to batch together page visits and send a bulk request every x minute. Perhaps every 15 minutes when the token refreshes.

**Comment by fullakingi** [comment]
Awesome! Glad it helped. I like the principle of having your own analytics built into your app instead of third party.

**Comment by fullakingi** [comment]
Just installed plausible.io analytics and thinking through this with regards to general reporting on user acquisition and funnel analysis (entreprenuer-level). An option could be to allow a logon event (user session start or refresh token)?  This way user data could be aggregated by the external provider as well?

**Comment by elitan** [comment]
We’ve decided to only fix bugs and refactors on Hasura Backend Plus from now on because we’re working on a new auth + storage service for Hasura. Currently, these new repositories are private but will be open-sourced soon. 

We’ll have your issue in mind when developing the new services. So thanks for filing this issue

 This means I’ll close this issue for now.
