### ISSUE TITLE
Store email templates in database instead of files

### ISSUE THREAD

**Issue by elitan** [nhost/hasura-backend-plus#511]
Can we store email templates in an `auth.email_templates` table instead of in files?

That would save us one mounting dependency.

Relevant: https://github.com/nhost/hasura-backend-plus/issues/323

**Comment by plmercereau** [comment]
I think you would probably move the complexity elsewhere: how then to maintain the state of a specific HBP application?
For the moment, If the developper modifies a file, the change is quite easy to track on a git repo, and a new deployment from the last commit would reflect the changes in the templates.
In storing templates in the DB, yes, we have one less mounting point in the docker stack, but we would then need to find a way to simplify the migration process from one commit to another...
The Hasura CLI `console` command won't be of any help as it only track changes in the schema, not the data.

**Comment by elitan** [comment]
It could be tracked using Hasura migrations. Not by using the Hasura CLI console but by creating migrations manually.

We could add the initial `INSERT INTO` migrations as part of HBP and then developers can track their own `UPDATE` migrations as part of their regular Hasura migrations.

**Comment by plmercereau** [comment]
well, sure, but DX will be quite hampered by asking developers to manually code SQL scripts and create their Hasura migration files, compared to coding a single html-based template

**Comment by RubenVanEldik** [comment]
I'm not a big fan of this either. I'm using [MailMason](https://postmarkapp.com/mailmason) to generate my email templates. Right now my dockerfile automatically retrieves the output of MailMason and puts in the `/custom/emails` folder. This would all become a lot harder when this is moved to the database.

**Comment by aaronhayes** [comment]
> It could be tracked using Hasura migrations. Not by using the Hasura CLI console but by creating migrations manually.

> We could add the initial INSERT INTO migrations as part of HBP and then developers can track their own UPDATE migrations as part of their regular Hasura migrations.

As someone that has lots of custom SQL functions tracked/managed in hasura. Comparing SQL changes in migrations is very difficult. As each migration is a new `folder/up.sql` file you cannot compare files directly. You have to look back to find the most recent change to the function, then compare two different files, this has to be done manually.

The benefits from doing this don't come close to the poor DX this will bring (IMO).

**Comment by elitan** [comment]
Relevant: https://github.com/nhost/hasura-backend-plus/issues/417

**Comment by nikolowry** [comment]
Is there any documentation concerning setting up email and email templates? The site has nothing: f662d62c9c7ec6c59e11951e349aaf4c and the 500 Internal Error I'm getting when trying to trigger a test email isn't helping either
