### ISSUE TITLE
Sign Up / Login with LinkedIn throws error 500

### ISSUE THREAD

**Issue by alveshelio** [nhost/hasura-backend-plus#522]
I'm having an issue with LinkedIn, when I try to either login or sign up with LinkedIn I'm betting a 500 error:
![image](https://user-images.githubusercontent.com/8176422/118850607-dddab500-b8c8-11eb-9c5a-44603d7260c3.png)

**Comment by elitan** [comment]
Fixed in https://github.com/nhost/hasura-backend-plus/pull/526
