### ISSUE TITLE
v2.5.0 issues with local dev cli nhost dev 

### ISSUE THREAD

**Issue by pjindal91** [nhost/hasura-backend-plus#542]
1) Issue related to https://github.com/nhost/hasura-backend-plus/releases/tag/v2.5.0. Right now has to manually add the environment variable in .env.development file. This is difficult to predict and goes against the principal of least surprises. Potentially can add it here  https://github.com/nhost/cli/blob/dd6ad5be8ac76bd812fa64af4153eb807cf7d89f/src/util/compose.js#L88

2) Even after fixing the above, getting error below. v2.4.0 works fine. I dont know what migration library is doing, but can see a programmatic bug here https://github.com/nhost/hasura-backend-plus/pull/507/files#r641900749 which is missing the catch block.

Applying migrations
(node:28) UnhandledPromiseRejectionWarning: Error: Migration failed. Reason: relation "migrations" does not exist
    at /app/node_modules/postgres-migrations/dist/migrate.js:63:27
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /app/node_modules/postgres-migrations/dist/with-lock.js:25:28
    at async Object.applyMigrations (/app/dist/shared/migrations.js:13:9)
    at async start (/app/dist/ts-start.js:7:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:28) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:28) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by ArieJones** [comment]
I have been looking at this today .. the second issue appears to be related to the postgres-migrations package.. someone else is running into the same issue. 

https://github.com/ThomWright/postgres-migrations/issues/59

trying to deduce what table their package is looking for and add it in to see if it addresses the matter 

fingers crossed

**Comment by ArieJones** [comment]
Yeah so that was the problem... I have posted an answer on the link to the problem in the postgres-migrations repo.. 

but essentially.. we need to update the default search_path of the postegres user to include auth if we are going to keep the migrations table out of the public schema. 

`ALTER USER postgres SET search_path TO "$user", public, auth`

will solve the issue.. 

@elitan you'll have to have an update made to add this path into the postgres users default path and then it should address the issue.

**Comment by ArieJones** [comment]
@pjindal91 you first issue is already being addressed in a PR in the CLI repo 

[https://github.com/nhost/cli/pull/91](https://github.com/nhost/cli/pull/91)

**Comment by pjindal91** [comment]
> @pjindal91 you first issue is already being addressed in a PR in the CLI repo
> 
> [nhost/cli#91](https://github.com/nhost/cli/pull/91)

Perfecto! 

I will try out your suggestion for migrations in a bit. Right now fiddling with the custom api 😄 

Thanks for your help!
