### ISSUE TITLE
AUTO_MIGRATE removed but still in .env.example and documentation

### ISSUE THREAD

**Issue by joshmedeski** [nhost/hasura-backend-plus#561]
I see the AUTO_MIGRATE functionality was removed, see https://github.com/nhost/hasura-backend-plus/commit/85c3d1490aead9550d22c234425fe33da12f1463

In the environmental variables, this should be removed. It would even be helpful to include an error message if that variable is set to true to let users know it is no longer supported.

**Comment by joshmedeski** [comment]
I noticed the [migrations documentation](https://nhost.github.io/hasura-backend-plus/configuration.html#apply-migrations-for-a-new-installation) talks about Hasura handling the migrations. It would be good to mention what the `AUTO_MIGRATE` feature does on HBP and how to combine it with Hasura's migrations.

**Comment by elitan** [comment]
Yes. Thanks for spotting this.

For reference: HBP now handles its own migrations (https://github.com/nhost/hasura-backend-plus/pull/507) and will handle its own metadata soon (https://github.com/nhost/hasura-backend-plus/pull/546).

**Comment by adevofficial** [comment]
@elitan what are the issues with hasura based cli migrations #546 #507
can we persist "AUTO_MIGRATE" env so that we can override the default behavior we can set "AUTO_MIGRATE" as true by default right ?

**Comment by elitan** [comment]
`AUTO_MIGRATE` is not really related to the fact that HBP will handle its own migrations and metadata.

`AUTO_MIGRATE` was previously used to auto migrate from HBP v1 to HBP v2.

Generally, I don't think we'll allow to opt-out of HBP's own migrations and metadata.
