### ISSUE TITLE
Problem to get Hasura's metadata

### ISSUE THREAD

**Issue by migsar** [nhost/hasura-backend-plus#582]
After doing a clean install with v2.5.2, when I try to register a user I get the following:

```
graphql-engine_1       | {"type":"http-log","timestamp":"2021-06-09T06:32:47.632+0000","level":"error","detail":{"operation":{"user_vars":{"x-hasura-role":"admin"},"error":{"path":"$","error":"no mutations exist","code":"validation-failed"},"request_id":"7803734d-f055-4d20-a498-68422126926f","response_size":68,"query":{"variables":{"account":{"email":"m@example.com","account_roles":{"data":[{"role":"user"}]},"user":{"data":{"display_name":"m@example.com"}},"ticket":"b67f1142-60f2-4755-8d35-be421d900ab1","active":true,"password_hash":"$2a$10$nHTcBuPvmWHX5nI/o7Ju.uGkKmPP4cdn0VdNvnbVfo6s185HQ0G/.","default_role":"user","ticket_expires_at":"2021-06-09T07:32:47.637Z"}},"query":"mutation ($account: auth_accounts_insert_input!) {\n  insert_auth_accounts(objects: [$account]) {\n    affected_rows\n    returning {\n      ...accountFragment\n    }\n  }\n}\n\nfragment accountFragment on auth_accounts {\n  id\n  active\n  default_role\n  account_roles {\n    role\n  }\n  user {\n    id\n    display_name\n  }\n  is_anonymous\n  ticket\n  email\n  new_email\n  otp_secret\n  mfa_enabled\n  password_hash\n}\n"}},"http_info":{"status":200,"http_version":"HTTP/1.1","url":"/v1/graphql","ip":"172.19.0.3","method":"POST","content_encoding":null}}}
```

Bottomline: `"error":"no mutations exist"`

After that I can confirm in Hasura's console that there is no schema and tables are not being tracked.
  
I saw #546 is still open. What is the recommended way to handle Hasura's metadata at this point?

**Comment by elitan** [comment]
Either wait for https://github.com/nhost/hasura-backend-plus/pull/546 or apply the metadata [here](https://github.com/nhost/hasura-backend-plus/tree/master/db/hasura/metadata) manually.

**Comment by migsar** [comment]
Thanks, it is working now but I had to delete the following lines [/db/hasura/metadata/tables.yaml#L101-L106](https://github.com/nhost/hasura-backend-plus/blob/master/db/hasura/metadata/tables.yaml#L101-L106), not sure if that will have some consequence later when configuring email templates or some particular provider.

**Comment by elitan** [comment]
Ah, yea that's because we're in the process of releasing a new major version. Things are a bit unstable at the moment. Glad you got it working :)
