### ISSUE TITLE
How do you deploy?

### ISSUE THREAD

**Issue by joshmedeski** [nhost/hasura-backend-plus#583]
I'd like to add documentation for how to self-host the hasura-backend-plus project through a service like AWS (what my agency uses).

I'm currently attempting to use ECS with EC2 instances but haven't figured out how to host the `./custom` directory so my private key and email templates are properly connected.

The other method I expect will work is to build my own hasura-backed-plus Docker image including my changes in the `./custom` directory and host it on AWS's ECR and deploy it through ECS Fargate. But that seems like more work to maintain over time.

 I'll also be setting up CI with GitHub Actions. Once it's fully working I'll add what I did to the documentation ;)

Any suggestions on how to deploy as a Docker container and include the custom directory?

**Comment by elitan** [comment]
It should be enough to mount the `custom` directory like this:

```yaml
    volumes:
      - './custom:/app/custom'
```

if you have the `custom/` folder and the `docker-compose.yaml` in the same directory.

For v2.5.x you can use this `custom/` folder: https://github.com/nhost/hasura-backend-plus/tree/magic-link-hotfix/custom

**Comment by joshmedeski** [comment]
I got things working on an EC2.
