### ISSUE TITLE
How to delete database

### ISSUE THREAD

**Issue by wave-light** [nhost/hasura-backend-plus#598]
Hi, I'd like to delete my database and re-run my migrations.
Can you tell me how this can easily be done?
And, is it advisable to do this?

Also, I cannot access my database via the console. I tried to access it using `docker exec -ti hasura-backend-plus_postgres_1 psql -U postgres` but it didn't contain the expected schemas: `public`, `auth`, `pg_temp_1`, `pg_toast`, `pg_toast_temp_1`
Can somebody please advide how I can access the database via the console?
Thanks

**Comment by elitan** [comment]
Do you have a docker-compose.yaml file that you're using?

Either you need to delete the docker volume or remove the folder on the host system (ex `db_data`) if you're using ex :

```yaml
    volumes:
      - "./db_data:/var/lib/postgresql/data"
```

**Comment by elitan** [comment]
If you're using docker volumes: https://docs.tibco.com/pub/mash-local/4.3.0/doc/html/docker/GUID-BD850566-5B79-4915-987E-430FC38DAAE4.html

If you're mounting the database to the host system:

1. `docker-compose down`
2. remove folder locally (ex `rm -rf db_data`)
3. `docker-compose up -d`
