### ISSUE TITLE
Issue: had to manually track tables and foreign-key relationships

### ISSUE THREAD

**Issue by swapnil2525kangralkar** [nhost/hasura-backend-plus#601]
- I had to manually track tables and foreign-key relationships. 
- Also,needed to add user relation in auth.accounts otherwise registration was failing.
- Checking on local using docker-compose. Please check below screenshots.

Environment: 
- Localhost: docker-compose
- nhost/hasura-backend-plus:v2.6.1
- nhost/postgres:12 
- hasura/graphql-engine:v2.0.1

![HBP-logs](https://user-images.githubusercontent.com/21957538/123515291-6dd40180-d6b4-11eb-9e26-cdfd91282f98.png)
![auth_tables](https://user-images.githubusercontent.com/21957538/123515287-6a407a80-d6b4-11eb-84ca-8c2e9dcc38f6.png)

**Comment by elitan** [comment]
Fixed in https://github.com/nhost/hasura-backend-plus/releases/tag/v2.7.0
