### ISSUE TITLE
Incorrect way to set configuration though environment variables

### ISSUE THREAD

**Issue by plmercereau** [nhost/hasura-backend-plus#609]
[This piece of code](https://github.com/nhost/hasura-backend-plus/blob/b4bfaf77fe24f17ed52a7dc5d5d289a6b9eaa9a2/src/shared/config/authentication/index.ts#L13-L19) and [this one](https://github.com/nhost/hasura-backend-plus/blob/b4bfaf77fe24f17ed52a7dc5d5d289a6b9eaa9a2/src/shared/config/storage.ts#L8-L12) are incorrect.

For instance, despite setting `STORAGE_ENABLED` to `false`, storage will be enabled as ` castBooleanEnv('STORAGE_ENABLED') || castBooleanEnv('STORAGE_ENABLE') || true` will then return `true`.

... and as other storage environment variables are not set, [it will cause the server failing to start](https://github.com/nhost/hasura-backend-plus/blob/master/src/env-vars-check.ts)...

**Comment by plmercereau** [comment]
Related to #600

**Comment by plmercereau** [comment]
same issue here
https://github.com/nhost/hasura-backend-plus/blob/b4bfaf77fe24f17ed52a7dc5d5d289a6b9eaa9a2/src/shared/config/application.ts#L77

**Comment by elitan** [comment]
Fixed in https://github.com/nhost/hasura-backend-plus/commit/b685de451bc7aefb19de6b19f5323855bd8bc1e6
