### ISSUE TITLE
no explanation when an environment variable is missing

### ISSUE THREAD

**Issue by plmercereau** [nhost/hasura-backend-plus#612]
https://github.com/nhost/hasura-backend-plus/blob/d4f51176a395f9803f463a956e9e3ca022c91288/src/env-vars-check.ts#L162

Will only throw `Invalid configuration` without giving the chance for the developper to know what has been wrongly configured

**Comment by Bomberus** [comment]
Were you able to get this project running in the first place?

**Comment by plmercereau** [comment]
Sure! Are you stuck? Although there's a bit of backlog in fixing bugs, the Nhost team usually provides good support on Discord:
https://discord.com/invite/9V7Qb2U

**Comment by elitan** [comment]
This env-vars-check has been removed from the current `master` branch as we're only focusing on fixing bugs and refactoring right now.
