### ISSUE TITLE
JWT_KEY should not be mandatory

### ISSUE THREAD

**Issue by plmercereau** [nhost/hasura-backend-plus#615]
https://github.com/nhost/hasura-backend-plus/blob/48c24d346a66f7e892cc820d9cbff37f8ba52f03/src/env-vars-check.ts#L13

`JWT_KEY` is not required when algorithm is `RSA`:

https://github.com/nhost/hasura-backend-plus/blob/d4f51176a395f9803f463a956e9e3ca022c91288/src/shared/jwt.ts#L19-L42

**Comment by elitan** [comment]
This check has been removed from the current `master` branch.
