### ISSUE TITLE
Provision of working examples for auth requests

### ISSUE THREAD

**Issue by dewulf** [nhost/hasura-backend-plus#618]
Dear Colleagues!
I'm really struggling to understand the API and get all the requests working. The documentation is unfortunately not helpful (would like to propose help in updating it - are there any guidelines that you have?). 
In detail I cannot get working the following requests by now:
- /auth/token/refresh (getting 404 "not found")
- /auth/token/revoke (getting "Not logged in" - permission_variables is somehow not set in revoke.ts - my query string is as follows http://host:3000/auth/token/revoke?permission_variables={'user-id': 'e076a8f4-7b3c-4b39-a758-836869212824'})

Other requests I'm currently testing. If there is something more I will update this issue. 

It would be really helpful to provide some working examples of requests to understand the API better. Can help with this when I have understood how its working

**Comment by michaelschort** [comment]
Did you pass a valid JWT as authorization header? 

In Postman pass just the three encoded strings wich are divided by a point (without the rest of the /login or /register response payload) as the token. 

The role and user-id are embedded in the JWT. It should not be necessary to pass these values as parameters with the request.

**Comment by elitan** [comment]
Try to follow the new docs: 

https://nhost.github.io/hasura-backend-plus/docs/getting-started/setup
