### ISSUE TITLE
[v2] JWKS endpoint?

### ISSUE THREAD

**Issue by plmercereau** [nhost/hasura-backend-plus#62]
Hi Johan,
First of all many thanks for this very nice repo! I am actually considering using it instead of the [scrappy attempt](https://github.com/platyplus/authentication-server) I did a few months ago (and another ongoing attempt in this [monorepo](https://github.com/platyplus/platyplus)).
Did you ever considered setting a JWKS endpoint, so Hasura could get its JWK public key from HBP? It would help centralise the keys into one service (HBP), and we could then even consider an automatic keys rotation. What do you think about that?
Best,
Pilou

**Comment by elitan** [comment]
Hi and thanks. I hope it bring some value to other developers too! :)

Sure, that would be possible. Not a priority for me right now.

Do you have a specific use case where you need a JWKS endpoint instead of using a secret key?

**Comment by plmercereau** [comment]
Hi,
Not a strong requirement, but it would allow to centralise the handling and sharing of keys into one single service (HBP), rather than having to spread the key into multiple services (e.g. HPB and Hasura).
For instance, if you have another service that has to validate JWTs, they would require to get the public key defined in its environment variables. With a JWKS endpoint, you would only need to link the service to HPB, and then HPB would take care of the rest. It could be especially useful when you need to update the key, either because you want to change it on a regular basis, or because it has been compromised.
Another thing is that you don't want to share the secret key, whereas JWKS are fine to be shared. It allow then any third party service to validate the JWT if you make this endpoint available.
Does it make sense?
Anyway, I don't think it is too difficult to implement, and I would be happy to contribute if you find this could be of some value.
Best

**Comment by elitan** [comment]
Ah Ok. Now I undertand better. Thanks for the explanation.

It should definitely be available!
