### ISSUE TITLE
GraphQL endpoint for files

### ISSUE THREAD

**Issue by MarcelloTheArcane** [nhost/hasura-backend-plus#72]
_I've had a quick look around, but I don't think there is such a thing as a GraphQL wrapper for Amazon AWS. Would it be preferable to develop this externally and import to HBP at a later date?_

---

It would be really useful to have a GraphQL endpoint for the file API in HBP. Ideally, it should be possible to create, read, update and delete files.

### Creating files

[Here is a specification for uploading files](https://github.com/jaydenseric/graphql-multipart-request-spec/blob/master/readme.md). The implementation will need a bit of work to smoothly work with AWS, particularly large files. This could be implemented at a later date, as there is already a workable upload solution.

It will either need a custom GraphQL type, or else require the file to be encoded as a base64 blob (very large files might prohibit this).

### Reading files

The [`listObjects`](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#listObjectsV2-property) provides a method for listing objects. It looks like you can get metadata for all objects like this, though I'm not sure how is best to implement the folder structure through GraphQL (i.e. folders and files in the same directory).

There's an issue of pagination that some users may face (1000 items maximum), but there are ways round that.

You might need to work out whether it would be more efficient to use [`headObject`](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#headObject-property) or `listObjects` depending on the GraphQL query.

### Updating files

I can't seem to find the appropriate endpoint for updating files, possibly you should delete and re-add the file.

### Deleting files

You can delete multiple objects with the [`deleteObjects`](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#deleteObjects-property) property, but I think you need to reference the unique ID assigned by the bucket. In order to delete in a GraphQL-compliant way (i.e. deleting by an arbitrary reference), you may need to get the bucket data before.

An idea for implementing into Nhost would be as a remote schema. Is it possible to create a new Hasura instance with preconfigured remote schemas? If so, you could add an authentication key as an environment variable.

**Comment by MarcelloTheArcane** [comment]
An alternative would be to make a separate project that would add a GraphQL server on top of https://backend-xxxxxxxx.nhost.io, and add it as a remote schema.

I'd be happy to do this, but I would need an endpoint to batch get and delete files.

**Comment by elitan** [comment]
I like the idea but I am not sure what the real benefit is other than "unify" everything under one GraphQL endpoint. I wont prioritize it but I think it could be "nice" to implement and provide.

**Comment by MarcelloTheArcane** [comment]
Okay, I'll think about making and external schema to go on top of the backend storage endpoint.

Would it be possible to have an endpoint that lists all the files that a user can see?

**Comment by elitan** [comment]
Yea an external schema make sense.

How would the resolver know what files a specific user would be allowed to interact with? Would you make use of storage  rules?

**Comment by MarcelloTheArcane** [comment]
It might need a bit of work here first. Firebase has a '[list items](https://firebase.google.com/docs/storage/web/list-files)' endpoint, which only works with their v2 permissions platform - would the current permissions strategy work with the AWS [`listObjects`](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#listObjectsV2-property) method?

**Comment by elitan** [comment]
Yes I think the `listObjects` method would work with the current storage rules. You just need to run every key (file) through the storage rules to make sure read access is allowed for that particular key (file).

**Comment by MarcelloTheArcane** [comment]
Okay cool. It's going to need some testing to see whether you can get the metadata (auth token) from the `listObjects` endpoint.

The example response in the documentation is this:

```js
data = {
  Contents: [
    {
      ETag: "\"70ee1738b6b21e2c8a43f3a5ab0eee71\"", 
      Key: "happyface.jpg", 
      LastModified: <Date Representation>, 
      Size: 11, 
      StorageClass: "STANDARD"
    }, 
    {
      ETag: "\"becf17f89c30367a9a44495d62ed521a-1\"", 
      Key: "test.jpg", 
      LastModified: <Date Representation>, 
      Size: 4192256, 
      StorageClass: "STANDARD"
    }
  ], 
  IsTruncated: true, 
  KeyCount: 2, 
  MaxKeys: 2, 
  Name: "examplebucket", 
  NextContinuationToken: "1w41l63U0xa8q7smH50vCxyTQqdxo69O3EmK28Bi5PcROI4wI/EyIJg==", 
  Prefix: ""
}
```

So it might need iterating on permissions _and_ to do a `headObject` on each key?

**Comment by MarcelloTheArcane** [comment]
Relevant issue: https://github.com/aws/aws-sdk-js/issues/1181

**Comment by MarcelloTheArcane** [comment]
Would it be possible to include a `files` table by default, like the tables for authentication?

It could be view only initially, and connect to the endpoints for creating and deleting files.

The schema could be based on the [`saved_file`](https://github.com/elitan/hasura-backend-plus/blob/master/src/storage/storage.js#L227) data:

- `originalname`
- `mimetype`
- `encoding`
- `key`
- `extension`
- `token`

**Comment by plmercereau** [comment]
Hello @MarcelloTheArcane ,
FYI HBP v2 is planned to implement lists, either for getting S3 object heads, or for downloading a zip file that contains multiple files.

As for the `files` tables, we don't think it's a good idea because it may complicate data sync between S3/minio and Posgtres, as we would not have a single source of truth anymore.
Example: if you update the `files` table, you could then trigger an update of the object headers, but what if another service is also connected to S3 and then directly changes the headers on S3, and not Postgres?

The main advantage to be able to upload files through a GraphQL endpoint would be to be able to unify the s3 heads/postgres schemas and to make some joins somehow, but it would make sense only if done within Hasura metadata system. And Hasura is not handling file upload...

I think this is something that can be considered at a later stage, maybe through Hasura Actions, but when [multipar file uploads](https://github.com/hasura/graphql-engine/issues/2419) would have been made available.

I hope it helps
