### ISSUE TITLE
Errors not handled?

### ISSUE THREAD

**Issue by dminkovsky** [nhost/hasura-backend-plus#84]
Thanks very much for this code. Reading it, I noticed these errors:

- https://github.com/elitan/hasura-backend-plus/blob/01e6b1b5f8ae4a6fd43c484ec27169a2ccbc9138/src/auth/auth.js#L144
- https://github.com/elitan/hasura-backend-plus/blob/01e6b1b5f8ae4a6fd43c484ec27169a2ccbc9138/src/auth/auth.js#L183

don't seem to be handled, like the error is handled at:

https://github.com/elitan/hasura-backend-plus/blob/01e6b1b5f8ae4a6fd43c484ec27169a2ccbc9138/src/auth/auth.js#L33

**Comment by elitan** [comment]
They should indeed. Thanks for pointing it out!
