### ISSUE TITLE
Allow selected permission variable to be null

### ISSUE THREAD

**Issue by MarcelloTheArcane** [nhost/hasura-backend-plus#86]
Currently, if I select a permission variable but this value is `null` for the user, the login hangs.

1. Create a new column in the `users` table, with a nullable field
2. Add this field to the permission variables in the NHost console
3. Try to log on.

I get a `502: Server timeout` error.

**Comment by MarcelloTheArcane** [comment]
I guess the error is here:

https://github.com/nhost/hasura-backend-plus/blob/01e6b1b5f8ae4a6fd43c484ec27169a2ccbc9138/src/auth/auth-functions.js#L15

Where `user[user_field]` is null, `(null).toString()` throws an error.

You could replace it with `user[user_field] && user[user_field].toString()`, which would be null if it doesn't exist.

**Comment by elitan** [comment]
Tricky bug and nice solution! :D
