### ISSUE TITLE
Migration guide between v1.1.4 to v1.2.2

### ISSUE THREAD

**Issue by aaronhayes** [nhost/hasura-backend-plus#92]
Does the new sql script migrate or just replace everything?

**Comment by elitan** [comment]
The SQL script (db-init.sq) is meant to be used on a fresh new installation.

I do not have a migration script. If you want to migrate, here are some tips from my current memory:

- Create a `auth` schema.
- Move all tables except `users`, `roles` and `user_roles` to the `auth` schema.
- Move `registration_data` from table `user_accounts` to `user`.
- Add `is_anonymous boolean DEFAULT false NOT NULL` to the `users` table.

Again, this is from the top of my memory.

**Comment by aaronhayes** [comment]
Yep that seemed to do the trick!

These are the SQL statements I ran for others:

1. `CREATE SCHEMA IF NOT EXISTS auth;`
2. `ALTER TABLE auth_providers SET SCHEMA auth;`
3. `ALTER TABLE refresh_tokens SET SCHEMA auth;`
4. `ALTER TABLE user_accounts SET SCHEMA auth;`
5. `ALTER TABLE user_providers SET SCHEMA auth;`
6. `ALTER TABLE users
          ADD COLUMN is_anonymous boolean DEFAULT false NOT NULL,
          ADD COLUMN register_data jsonb;`

**Comment by elitan** [comment]
Perfect!
