### ISSUE TITLE
[v2] Email (templates) support

### ISSUE THREAD

**Issue by elitan** [nhost/hasura-backend-plus#99]
Configurable e-mail support

### Env variables:

- Sender email address
- SMTP server host
- SMTP server port
- Server login username
- Server login password

### Email templates:

- Activate account (after register if AUTO_ACTIVATE is false)
- Forgot (Request new password)

### Routes affected:

- `/auth/register`
- `/auth/user/forgot`

**Comment by pnfcre** [comment]
I'm working on this at the moment 👍
